{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/darkcontent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/darkcontent"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/darkContent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle"]]},"metadata":{"title":"StatusBarNotificationSystemBarStyle.darkContent","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"text":"JDStatusBarNotificationSystemBarStyleDarkContent","kind":"identifier"}],"externalID":"c:@E@JDStatusBarNotificationSystemBarStyle@JDStatusBarNotificationSystemBarStyleDarkContent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"darkContent"}],"roleHeading":"Case","symbolKind":"case","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"darkContent","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"text":"Forces dark status bar contents (","type":"text"},{"type":"codeVoice","code":"UIStatusBarStyleDarkContent"},{"text":")","type":"text"}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/darkContent":{"title":"StatusBarNotificationSystemBarStyle.darkContent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleDarkContent"}],"abstract":[{"type":"text","text":"Forces dark status bar contents ("},{"code":"UIStatusBarStyleDarkContent","type":"codeVoice"},{"type":"text","text":")"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"darkContent","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/darkContent","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/darkcontent"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"kind":"symbol","type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"title":"StatusBarNotificationSystemBarStyle","abstract":[{"text":"Defines which ","type":"text"},{"type":"codeVoice","code":"UIStatusBarStyle"},{"type":"text","text":" should be used during presentation."}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","role":"symbol","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationSystemBarStyleDarkContent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"JDStatusBarNotificationSystemBarStyleDarkContent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleDarkContent"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"JDStatusBarNotificationSystemBarStyleDarkContent","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1darkContent\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1darkContent\/fragments","value":[{"text":"JDStatusBarNotificationSystemBarStyleDarkContent","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]},{"value":"JDStatusBarNotificationSystemBarStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}