{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/hashvalue"]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/hashValue","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"JDStatusBarNotification","relatedModules":["Swift"]}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@E@JDStatusBarNotificationSystemBarStyle","title":"hashValue","symbolKind":"property","extendedModule":"Swift","roleHeading":"Instance Property","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/RawRepresentable-Implementations"]]},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","type":"topic","abstract":[{"text":"Defines which ","type":"text"},{"code":"UIStatusBarStyle","type":"codeVoice"},{"type":"text","text":" should be used during presentation."}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"title":"StatusBarNotificationSystemBarStyle","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/hashValue":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/hashValue","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"abstract":[],"title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/hashvalue"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/rawrepresentable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JDStatusBarNotificationStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]},{"value":"JDStatusBarNotificationSystemBarStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments","value":[{"text":"JDStatusBarNotificationSystemBarStyle","kind":"identifier"}],"op":"replace"}]}]}