{"abstract":[{"type":"text","text":"Forces light status bar contents ("},{"type":"codeVoice","code":"UIStatusBarStyleLightContent"},{"type":"text","text":")"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lightContent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lightContent","kind":"identifier"}],"title":"StatusBarNotificationSystemBarStyle.lightContent","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"externalID":"c:@E@JDStatusBarNotificationSystemBarStyle@JDStatusBarNotificationSystemBarStyleLightContent","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleLightContent"}]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/lightcontent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/lightcontent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/lightContent","interfaceLanguage":"swift"},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/lightContent":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/lightContent","title":"StatusBarNotificationSystemBarStyle.lightContent","kind":"symbol","abstract":[{"type":"text","text":"Forces light status bar contents ("},{"type":"codeVoice","code":"UIStatusBarStyleLightContent"},{"type":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleLightContent"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/lightcontent","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lightContent","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","type":"topic","abstract":[{"text":"Defines which ","type":"text"},{"code":"UIStatusBarStyle","type":"codeVoice"},{"type":"text","text":" should be used during presentation."}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"title":"StatusBarNotificationSystemBarStyle","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationSystemBarStyleLightContent"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JDStatusBarNotificationSystemBarStyleLightContent","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"JDStatusBarNotificationSystemBarStyleLightContent","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"JDStatusBarNotificationStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1lightContent\/title","op":"replace","value":"JDStatusBarNotificationSystemBarStyleLightContent"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1lightContent\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleLightContent"}]},{"op":"replace","value":"JDStatusBarNotificationSystemBarStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationSystemBarStyle","kind":"identifier"}]}]}]}