{"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"],["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"seeAlsoSections":[{"title":"Default Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/light","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/dark"],"generated":true}],"abstract":[{"text":"The default style. This is used when no other style was provided and the","type":"text"},{"text":" ","type":"text"},{"text":"default style wasn’t replaced by the user. This is a dynamic style matching","type":"text"},{"type":"text","text":" "},{"text":"the ","type":"text"},{"type":"codeVoice","code":"light"},{"text":" style in light mode and ","type":"text"},{"type":"codeVoice","code":"dark"},{"type":"text","text":" style in dark mode."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/defaultstyle"]},{"paths":["\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/defaultstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/defaultStyle"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"defaultStyle","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"externalID":"c:@E@JDStatusBarNotificationIncludedStyle@JDStatusBarNotificationIncludedStyleDefaultStyle","role":"symbol","symbolKind":"case","title":"IncludedStatusBarNotificationStyle.defaultStyle","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultStyle"}],"roleHeading":"Case","navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleDefaultStyle","kind":"identifier"}]},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle/defaultStyle":{"navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleDefaultStyle","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The default style. This is used when no other style was provided and the"},{"text":" ","type":"text"},{"text":"default style wasn’t replaced by the user. This is a dynamic style matching","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the "},{"type":"codeVoice","code":"light"},{"text":" style in light mode and ","type":"text"},{"code":"dark","type":"codeVoice"},{"type":"text","text":" style in dark mode."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultStyle","kind":"identifier"}],"title":"IncludedStatusBarNotificationStyle.defaultStyle","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/defaultstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/defaultStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","kind":"symbol","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"notification without creating your own custom style."}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"type":"topic","title":"IncludedStatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"kind":"symbol","type":"topic","title":"NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle/dark":{"navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleDark","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A nearly black background with a nearly white text."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dark"}],"title":"IncludedStatusBarNotificationStyle.dark","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/dark","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/dark"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle/light":{"title":"IncludedStatusBarNotificationStyle.light","kind":"symbol","navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleLight","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"light","kind":"identifier"}],"abstract":[{"type":"text","text":"A white background with a gray text."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/light","type":"topic","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/light","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","kind":"symbol","abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter","fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"type":"topic","title":"JDStatusBarNotificationPresenter","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"JDStatusBarNotificationIncludedStyleDefaultStyle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"JDStatusBarNotificationIncludedStyleDefaultStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"title":"Default Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/light","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/dark"]}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyleDefaultStyle"}]}],"kind":"declarations"}},{"value":"JDStatusBarNotificationIncludedStyleDefaultStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1defaultStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1defaultStyle\/fragments","value":[{"text":"JDStatusBarNotificationIncludedStyleDefaultStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","value":"JDStatusBarNotificationIncludedStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationIncludedStyle","kind":"identifier"}],"op":"replace"},{"value":"JDStatusBarNotificationIncludedStyleDark","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1dark\/title","op":"replace"},{"value":[{"text":"JDStatusBarNotificationIncludedStyleDark","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1dark\/fragments"},{"value":"JDStatusBarNotificationIncludedStyleLight","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1light\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1light\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyleLight"}]}]}]}