{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/success"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"success"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"A green background with a white text."}],"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleSuccess","kind":"identifier"}],"role":"symbol","externalID":"c:@E@JDStatusBarNotificationIncludedStyle@JDStatusBarNotificationIncludedStyleSuccess","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"success","kind":"identifier"}],"modules":[{"name":"JDStatusBarNotification"}],"title":"IncludedStatusBarNotificationStyle.success","symbolKind":"case"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/success"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/success"]}],"kind":"symbol","references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle/success":{"type":"topic","abstract":[{"type":"text","text":"A green background with a white text."}],"navigatorTitle":[{"text":"JDStatusBarNotificationIncludedStyleSuccess","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle\/success","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle\/success","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"title":"IncludedStatusBarNotificationStyle.success"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"role":"symbol","title":"IncludedStatusBarNotificationStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"notification without creating your own custom style."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationIncludedStyleSuccess"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JDStatusBarNotificationIncludedStyleSuccess","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"JDStatusBarNotificationIncludedStyleSuccess","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"JDStatusBarNotificationIncludedStyleSuccess","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1success\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle~1success\/fragments","value":[{"text":"JDStatusBarNotificationIncludedStyleSuccess","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","value":"JDStatusBarNotificationIncludedStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyle"}]}]}]}