{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment\/left"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment\/left"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment\/left","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Always align left. Text is center aligned unlless it touches the left view. If it does touch the left view, the text turns left aligned too."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"title":"StatusBarNotificationLeftViewAlignment.left","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@JDStatusBarNotificationLeftViewAlignment@JDStatusBarNotificationLeftViewAlignmentLeft","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentLeft"}]},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment"],["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment"]]},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment":{"role":"symbol","title":"StatusBarNotificationLeftViewAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"abstract":[],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment/left":{"role":"symbol","title":"StatusBarNotificationLeftViewAlignment.left","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"abstract":[{"type":"text","text":"Always align left. Text is center aligned unlless it touches the left view. If it does touch the left view, the text turns left aligned too."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentLeft"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment\/left"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"role":"symbol","title":"StatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"role":"symbol","title":"NotificationPresenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationPresenter"}],"abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"type":"text","text":" "},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationLeftViewAlignmentLeft"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentLeft"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentLeft"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/title","value":"JDStatusBarNotificationLeftViewAlignment"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment~1left\/title","value":"JDStatusBarNotificationLeftViewAlignmentLeft"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment~1left\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}