{"abstract":[{"type":"text","text":"Defines the animation used during presentation and dismissal of the notification."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animationType","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatusBarNotificationAnimationType","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType\/move"}]}]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/animationtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/animationtype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"animationType"}],"externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)animationType","symbolKind":"property","roleHeading":"Instance Property","title":"animationType","modules":[{"name":"JDStatusBarNotification"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType","kind":"typeIdentifier","text":"StatusBarNotificationAnimationType"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"seeAlsoSections":[{"title":"Notification Bar Behavior","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold"]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","interfaceLanguage":"swift"},"sections":[],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"role":"symbol","abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype","type":"topic","title":"StatusBarNotificationAnimationType","navigatorTitle":[{"text":"StatusBarNotificationAnimationType","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationAnimationType"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/animationType":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/animationtype","navigatorTitle":[{"text":"animationType","kind":"identifier"}],"abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"role":"symbol","title":"animationType","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType","kind":"typeIdentifier","text":"StatusBarNotificationAnimationType"}],"kind":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canTapToHold":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/cantaptohold","navigatorTitle":[{"text":"canTapToHold","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines if the bar can be touched to prevent a dismissal until the tap is released. Default is "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol","title":"canTapToHold","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canTapToHold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType/move":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype\/move","abstract":[{"type":"text","text":"Slide in from the top of the screen and slide back out to the top. This is the default."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType\/move","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"move"}],"navigatorTitle":[{"text":"JDStatusBarNotificationAnimationTypeMove","kind":"identifier"}],"title":"StatusBarNotificationAnimationType.move"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canDismissDuringUserInteraction":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/candismissduringuserinteraction","navigatorTitle":[{"text":"canDismissDuringUserInteraction","kind":"identifier"}],"abstract":[{"text":"Defines if the bar is allowed to be dismissed while the user touches or pans the view.","type":"text"}],"role":"symbol","title":"canDismissDuringUserInteraction","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canDismissDuringUserInteraction","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"text":"A Style defines the appeareance of a notification.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canSwipeToDismiss":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/canswipetodismiss","navigatorTitle":[{"text":"canSwipeToDismiss","kind":"identifier"}],"abstract":[{"text":"Defines if the bar can be dismissed by the user swiping up. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"role":"symbol","title":"canSwipeToDismiss","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canSwipeToDismiss"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"animationType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"animationType"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold"],"generated":true,"title":"Notification Bar Behavior"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"JDStatusBarNotificationAnimationType","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationType"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title","value":"JDStatusBarNotificationAnimationType"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationAnimationType"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments","op":"replace"},{"value":"animationType","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"animationType"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/fragments","op":"replace"},{"value":"canTapToHold","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/fragments","value":[{"kind":"identifier","text":"canTapToHold"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType~1move\/title","op":"replace","value":"JDStatusBarNotificationAnimationTypeMove"},{"op":"replace","value":[{"text":"JDStatusBarNotificationAnimationTypeMove","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType~1move\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/title","op":"replace","value":"canDismissDuringUserInteraction"},{"value":[{"kind":"identifier","text":"canDismissDuringUserInteraction"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/fragments"},{"value":"JDStatusBarNotificationStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]},{"value":"canSwipeToDismiss","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/fragments","value":[{"kind":"identifier","text":"canSwipeToDismiss"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}