{"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/backgroundStyle"},"kind":"symbol","seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle"],"title":"Styling the background"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/backgroundstyle"]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/backgroundstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"title":"backgroundStyle","roleHeading":"Instance Property","externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)backgroundStyle","navigatorTitle":[{"kind":"identifier","text":"backgroundStyle"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"backgroundStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatusBarNotificationBackgroundStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationBackgroundStyle","kind":"typeIdentifier"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationBackgroundStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","kind":"typeIdentifier","text":"StatusBarNotificationBackgroundStyle"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"inlineContent":[{"text":"That includes the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundColor"},{"type":"text","text":","},{"text":" ","type":"text"},{"type":"text","text":"the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundType"},{"text":" ","type":"text"},{"text":"and the ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/pillStyle","isActive":true,"type":"reference"},{"text":" (See ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle"},{"text":").","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/backgroundStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/backgroundStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/backgroundstyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationBackgroundStyle","text":"StatusBarNotificationBackgroundStyle","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"backgroundStyle","kind":"identifier"}],"title":"backgroundStyle","kind":"symbol","abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle":{"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"kind":"symbol","navigatorTitle":[{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationBackgroundStyle"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","title":"StatusBarNotificationBackgroundStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/pillStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/pillStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/pillstyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pillStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatusBarNotificationPillStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationPillStyle"}],"role":"symbol","navigatorTitle":[{"text":"pillStyle","kind":"identifier"}],"title":"pillStyle","kind":"symbol","abstract":[{"type":"text","text":"Defines the appeareance of the pill, when using "},{"isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","type":"reference"}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/backgroundType":{"title":"backgroundType","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@JDStatusBarNotificationBackgroundType","text":"StatusBarNotificationBackgroundType"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundType","abstract":[{"text":"The background type. Default is ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","isActive":true}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/backgroundtype","navigatorTitle":[{"text":"backgroundType","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationPillStyle":{"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationpillstyle","navigatorTitle":[{"text":"StatusBarNotificationPillStyle","kind":"identifier"}],"role":"symbol","title":"StatusBarNotificationPillStyle","abstract":[{"type":"text","text":"Defines the appeareance of the pill, when using "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","isActive":true,"type":"reference"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationPillStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/systemStatusBarStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/systemstatusbarstyle","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"systemStatusBarStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@JDStatusBarNotificationSystemBarStyle","text":"StatusBarNotificationSystemBarStyle","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"systemStatusBarStyle"}],"title":"systemStatusBarStyle","kind":"symbol","abstract":[{"text":"Defines which ","type":"text"},{"code":"UIStatusBarStyle","type":"codeVoice"},{"text":" should be used during presentation.","type":"text"}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/backgroundColor":{"title":"backgroundColor","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/backgroundcolor","kind":"symbol","abstract":[{"text":"The background color of the notification bar","type":"text"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundColor","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"type":"topic","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","title":"StatusBarNotificationBackgroundType.pill","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pill","kind":"identifier"}],"navigatorTitle":[{"text":"JDStatusBarNotificationBackgroundTypePill","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"backgroundStyle","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"backgroundStyle"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Styling the background","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationBackgroundStyle","text":"JDStatusBarNotificationBackgroundStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"backgroundStyle"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1backgroundStyle\/title","value":"backgroundStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1backgroundStyle\/fragments","value":[{"text":"backgroundStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"value":"JDStatusBarNotificationBackgroundStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/title"},{"value":[{"text":"JDStatusBarNotificationBackgroundStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/fragments","op":"replace"},{"value":"pillStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1pillStyle\/title"},{"value":[{"text":"pillStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1pillStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundType\/title","op":"replace","value":"backgroundType"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundType\/fragments","value":[{"text":"backgroundType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/title","op":"replace","value":"JDStatusBarNotificationPillStyle"},{"value":[{"text":"JDStatusBarNotificationPillStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/fragments","op":"replace"},{"op":"replace","value":"systemStatusBarStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1systemStatusBarStyle\/title"},{"value":[{"kind":"identifier","text":"systemStatusBarStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1systemStatusBarStyle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundColor\/title","value":"backgroundColor","op":"replace"},{"value":[{"kind":"identifier","text":"backgroundColor"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundColor\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title","value":"JDStatusBarNotificationBackgroundTypePill","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments"}]}]}