{"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canTapToHold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold","isActive":true,"type":"reference"},{"type":"text","text":" is "},{"code":"true","type":"codeVoice"},{"type":"text","text":" "},{"text":"and ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","type":"reference","isActive":true},{"text":" is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":","},{"text":" ","type":"text"},{"text":"the user can tap the notification to prevent it from being dismissed until the tap is released.","type":"text"}]},{"inlineContent":[{"type":"text","text":"If you are utilizing a custom view and need custom touch handling (e.g. for a button), you should set this to "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Under the hood this enables\/disables the internal "},{"type":"codeVoice","code":"LongPressGestureRecognizer"},{"text":".","type":"text"}],"type":"paragraph"}]}],"metadata":{"title":"canTapToHold","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"canTapToHold"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"canTapToHold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)canTapToHold","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/cantaptohold"]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/cantaptohold"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Defines if the bar can be touched to prevent a dismissal until the tap is released. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"seeAlsoSections":[{"generated":true,"title":"Notification Bar Behavior","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canTapToHold":{"kind":"symbol","abstract":[{"text":"Defines if the bar can be touched to prevent a dismissal until the tap is released. Default is ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canTapToHold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"canTapToHold","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/cantaptohold","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canTapToHold"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canDismissDuringUserInteraction":{"kind":"symbol","abstract":[{"type":"text","text":"Defines if the bar is allowed to be dismissed while the user touches or pans the view."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"canDismissDuringUserInteraction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/candismissduringuserinteraction","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","title":"canDismissDuringUserInteraction","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canDismissDuringUserInteraction"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/animationType":{"kind":"symbol","abstract":[{"type":"text","text":"Defines the animation used during presentation and dismissal of the notification."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType","text":"StatusBarNotificationAnimationType"}],"role":"symbol","title":"animationType","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/animationtype","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationType"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canSwipeToDismiss":{"kind":"symbol","abstract":[{"type":"text","text":"Defines if the bar can be dismissed by the user swiping up. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canSwipeToDismiss","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/canswipetodismiss","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","title":"canSwipeToDismiss","type":"topic","navigatorTitle":[{"text":"canSwipeToDismiss","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"canTapToHold","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"canTapToHold"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss"],"generated":true,"title":"Notification Bar Behavior"}],"op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canTapToHold"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/title","op":"replace","value":"canTapToHold"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/fragments","op":"replace","value":[{"kind":"identifier","text":"canTapToHold"}]},{"value":"JDStatusBarNotificationStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/title","value":"canDismissDuringUserInteraction","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/fragments","value":[{"text":"canDismissDuringUserInteraction","kind":"identifier"}]},{"op":"replace","value":"animationType","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/fragments","value":[{"kind":"identifier","text":"animationType"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/title","value":"canSwipeToDismiss","op":"replace"},{"value":[{"text":"canSwipeToDismiss","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}