{"sections":[],"metadata":{"externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)leftViewStyle","navigatorTitle":[{"text":"leftViewStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"leftViewStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle","text":"StatusBarNotificationLeftViewStyle","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"JDStatusBarNotification"}],"title":"leftViewStyle","roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftViewStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatusBarNotificationLeftViewStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"seeAlsoSections":[{"generated":true,"title":"Styling supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle"]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/leftviewstyle"]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/leftviewstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"title":"StatusBarNotificationLeftViewStyle","kind":"symbol","navigatorTitle":[{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/leftViewStyle":{"type":"topic","navigatorTitle":[{"text":"leftViewStyle","kind":"identifier"}],"abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/leftviewstyle","title":"leftViewStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftViewStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatusBarNotificationLeftViewStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle"}],"role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"text":"A Style defines the appeareance of a notification.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/progressBarStyle":{"type":"topic","navigatorTitle":[{"text":"progressBarStyle","kind":"identifier"}],"abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/progressbarstyle","title":"progressBarStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle","text":"StatusBarNotificationProgressBarStyle","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"leftViewStyle","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"leftViewStyle","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle"],"generated":true,"title":"Styling supplementary views"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","text":"JDStatusBarNotificationLeftViewStyle","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"leftViewStyle","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","value":"JDStatusBarNotificationLeftViewStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","value":"leftViewStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/fragments","value":[{"text":"leftViewStyle","kind":"identifier"}],"op":"replace"},{"value":"JDStatusBarNotificationStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/title","op":"replace","value":"progressBarStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/fragments","op":"replace","value":[{"text":"progressBarStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}