{"seeAlsoSections":[{"title":"Styling supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle"],"generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"progressBarStyle"}],"externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)progressBarStyle","symbolKind":"property","roleHeading":"Instance Property","title":"progressBarStyle","modules":[{"name":"JDStatusBarNotification"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressBarStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle","text":"StatusBarNotificationProgressBarStyle"}]},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressBarStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"StatusBarNotificationProgressBarStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/progressbarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/progressbarstyle"]}],"abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"text":"A Style defines the appeareance of a notification.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/progressBarStyle":{"type":"topic","navigatorTitle":[{"text":"progressBarStyle","kind":"identifier"}],"abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/progressbarstyle","title":"progressBarStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progressBarStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle","text":"StatusBarNotificationProgressBarStyle","kind":"typeIdentifier"}],"role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","title":"StatusBarNotificationProgressBarStyle","abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/leftViewStyle":{"type":"topic","navigatorTitle":[{"text":"leftViewStyle","kind":"identifier"}],"abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/leftviewstyle","title":"leftViewStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftViewStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"StatusBarNotificationLeftViewStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"progressBarStyle","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"progressBarStyle","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":[{"title":"Styling supplementary views","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle"]}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"JDStatusBarNotificationProgressBarStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"progressBarStyle","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace","value":"JDStatusBarNotificationStyle"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"op":"replace","value":"progressBarStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/title"},{"value":[{"text":"progressBarStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","value":"JDStatusBarNotificationProgressBarStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarStyle"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/title","op":"replace","value":"leftViewStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/fragments","value":[{"text":"leftViewStyle","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}