{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textStyle"},{"text":": ","kind":"text"},{"text":"StatusBarNotificationTextStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle"}],"navigatorTitle":[{"text":"textStyle","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"JDStatusBarNotification"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)JDStatusBarNotificationStyle(py)textStyle","role":"symbol","title":"textStyle"},"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/textStyle","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Styling the text","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle"],"generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle","text":"StatusBarNotificationTextStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults: "},{"type":"codeVoice","code":"UIFontTextStyleFootnote"},{"type":"text","text":", color: "},{"type":"codeVoice","code":".gray"},{"type":"text","text":" and adjusts for dark mode."},{"text":" ","type":"text"},{"type":"text","text":"The title’s "},{"type":"codeVoice","code":"textColor"},{"text":" is also used for the activity indicator, unless an explicit ","type":"text"},{"type":"codeVoice","code":"leftViewStyle.tintColor"},{"type":"text","text":" is set."},{"text":" ","type":"text"},{"type":"text","text":"The title’s "},{"type":"codeVoice","code":"textOffsetY"},{"text":" affects both the title, the subtitle and the left-view. And also the progressBar when using ","type":"text"},{"type":"codeVoice","code":".center"},{"text":" positioning.","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"Defines the appeareance of the title label.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/textstyle"]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/textstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/textStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/textStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatusBarNotificationTextStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"textStyle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Defines the appeareance of the title label."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/textstyle","role":"symbol","title":"textStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationTextStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"type":"topic","abstract":[{"type":"text","text":"Defines the appeareance of a text label."}],"title":"StatusBarNotificationTextStyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationtextstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationTextStyle"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/subtitleStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"subtitleStyle"},{"text":": ","kind":"text"},{"text":"StatusBarNotificationTextStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle"}],"kind":"symbol","navigatorTitle":[{"text":"subtitleStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/subtitlestyle","abstract":[{"type":"text","text":"Defines the appeareance of the subtitle label."}],"role":"symbol","title":"subtitleStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"title":"StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"textStyle","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"textStyle","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle"],"title":"Styling the text","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle","text":"JDStatusBarNotificationTextStyle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"textStyle"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1textStyle\/title","value":"textStyle"},{"op":"replace","value":[{"kind":"identifier","text":"textStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1textStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/title","value":"JDStatusBarNotificationTextStyle","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationTextStyle"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1subtitleStyle\/title","value":"subtitleStyle","op":"replace"},{"value":[{"text":"subtitleStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1subtitleStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}