{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"basedOnIncludedStyle"},{"kind":"text","text":" "},{"kind":"internalParam","text":"basedOnStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prepare"},{"kind":"text","text":" "},{"kind":"internalParam","text":"prepareBlock"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle","text":"StatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle","text":"StatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":", so that this call can be used directly within a presentation call."}]}]},{"kind":"parameters","parameters":[{"name":"styleName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The styleName which will later be used to reference the added style."}]}]},{"name":"basedOnStyle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"},{"type":"text","text":", which you want to base your style on."}]}]},{"name":"prepareBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Provides an "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},{"type":"text","text":" instance based on the provided "},{"type":"codeVoice","code":"basedOnStyle"},{"type":"text","text":" for further customization."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The added style can be used in future presentations by utilizing the same "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" in e.g. "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:customStyle:)"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"If a style with the same name already exists, it will be replaced."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:basedonincludedstyle:prepare:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:basedonincludedstyle:prepare:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:basedOnIncludedStyle:prepare:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Adds a new custom style based on a specific included style."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"basedOnIncludedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prepare"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"addStyle(styleName:basedOnIncludedStyle:prepare:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)addStyleNamed:basedOnStyle:prepare:","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}]},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"seeAlsoSections":[{"title":"Style Modification","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateDefaultStyle(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"],"generated":true}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"role":"symbol","title":"IncludedStatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"abstract":[],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(styleName:prepare:)":{"role":"symbol","title":"addStyle(styleName:prepare:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prepare"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Adds a new custom style."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:prepare:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:prepare:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:customStyle:)":{"role":"symbol","title":"present(text:customStyle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"customStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"Present a notification using a specified "},{"type":"codeVoice","code":"customStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:customStyle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentWithText:customStyle:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:customstyle:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"role":"symbol","title":"NotificationPresenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationPresenter"}],"abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"type":"text","text":" "},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"role":"symbol","title":"StatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(styleName:basedOnIncludedStyle:prepare:)":{"role":"symbol","title":"addStyle(styleName:basedOnIncludedStyle:prepare:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addStyle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"basedOnIncludedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"prepare"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Adds a new custom style based on a specific included style."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:basedOnIncludedStyle:prepare:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:basedonincludedstyle:prepare:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/updateDefaultStyle(_:)":{"role":"symbol","title":"updateDefaultStyle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDefaultStyle"},{"kind":"text","text":"(("},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Defines a new default style."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateDefaultStyle(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateDefaultStyle:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/updatedefaultstyle(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addStyleNamed:basedOnStyle:prepare:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Style Modification","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateDefaultStyle(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"addStyleNamed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"styleName"},{"kind":"text","text":" "},{"kind":"identifier","text":"basedOnStyle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":")"},{"kind":"internalParam","text":"basedOnStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JDStatusBarNotificationStyle *(^)(JDStatusBarNotificationStyle *)","preciseIdentifier":"c:BF*$objc(cs)JDStatusBarNotificationStyle(#S2_)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"prepareBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","value":"JDStatusBarNotificationIncludedStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/title","value":"addStyleNamed:prepare:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:prepare:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:customStyle:)\/title","value":"presentWithText:customStyle:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:customStyle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:customStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:basedOnIncludedStyle:prepare:)\/title","value":"addStyleNamed:basedOnStyle:prepare:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:basedOnIncludedStyle:prepare:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1updateDefaultStyle(_:)\/title","value":"updateDefaultStyle:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1updateDefaultStyle(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDefaultStyle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}