{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(to:duration:completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(at:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)"],"title":"Display supplementary views","generated":true}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(to:duration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animateProgressBar","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","text":"Completion","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"symbolKind":"method","modules":[{"name":"JDStatusBarNotification"}],"externalID":"s:23JDStatusBarNotification0C9PresenterV015animateProgressB02to8duration10completionySd_SdyACcSgtF","title":"animateProgressBar(to:duration:completion:)"},"abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"code":"percentage","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateProgressBar"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"kind":"text","text":" "},{"text":"percentage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/Completion","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","text":"Completion","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"percentage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Relative progress from 0.0 to 1.0"}]}]},{"name":"animationDuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The duration of the animation from the current percentage to the provided percentage."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/Completion"},{"text":", which gets called once the progress bar animation finishes.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Animates the progress bar from the currently set "},{"code":"percentage","type":"codeVoice"},{"type":"text","text":" to the provided "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":" using the provided "},{"type":"codeVoice","code":"duration"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The progress bar will be styled according to the current "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","isActive":true,"type":"reference"},{"text":".","type":"text"}]}]}],"kind":"symbol","references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/Completion":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Completion"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/completion","type":"topic","navigatorTitle":[{"text":"Completion","kind":"identifier"}],"title":"NotificationPresenter.Completion","role":"symbol","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/Completion"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"kind":"symbol","type":"topic","title":"NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayProgressBar(at:)":{"kind":"symbol","title":"displayProgressBar(at:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"displayProgressBar"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(at:)","type":"topic","abstract":[{"text":"Displays a progress bar at the given ","type":"text"},{"code":"percentage","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayprogressbar(at:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayLeftView(_:)":{"kind":"symbol","title":"displayLeftView(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"displayLeftView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)","abstract":[{"text":"Displays a view on the left side of the text.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The layout is defined by the "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","type":"reference","isActive":true},{"type":"text","text":"."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayleftview(_:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayActivityIndicator(_:)":{"kind":"symbol","title":"displayActivityIndicator(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"displayActivityIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","abstract":[{"text":"Displays an activity indicator as the notifications left view.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayactivityindicator(_:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"title":"StatusBarNotificationLeftViewStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the appeareance of the progress bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"title":"StatusBarNotificationProgressBarStyle","type":"topic","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/animateProgressBar(to:duration:completion:)":{"kind":"symbol","title":"animateProgressBar(to:duration:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animateProgressBar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(to:duration:completion:)","type":"topic","abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"code":"percentage","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(to:duration:completion:)"}},"variantOverrides":[{"patch":[{"value":"JDStatusBarNotificationLeftViewStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","value":"JDStatusBarNotificationProgressBarStyle"},{"value":[{"text":"JDStatusBarNotificationProgressBarStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}