{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(toPercentage:animationDuration:completion:)"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(percentage:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)"],"title":"Display supplementary views"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animateProgressBar","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"toPercentage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"animationDuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)animateProgressBarToPercentage:animationDuration:completion:","title":"animateProgressBar(toPercentage:animationDuration:completion:)"},"abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"code":"percentage","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animateProgressBar","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toPercentage"},{"text":" ","kind":"text"},{"text":"percentage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"animationDuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"percentage","content":[{"inlineContent":[{"type":"text","text":"Relative progress from 0.0 to 1.0"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The duration of the animation from the current percentage to the provided percentage.","type":"text"}]}],"name":"animationDuration"},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"A "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","isActive":true,"type":"reference"},{"text":", which gets called once the progress bar animation finishes.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Animates the progress bar from the currently set ","type":"text"},{"code":"percentage","type":"codeVoice"},{"text":" to the provided ","type":"text"},{"type":"codeVoice","code":"percentage"},{"text":" using the provided ","type":"text"},{"type":"codeVoice","code":"animationDuration"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The progress bar will be styled according to the current ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle"},{"text":".","type":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(topercentage:animationduration:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(topercentage:animationduration:completion:)"]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/animateProgressBar(toPercentage:animationDuration:completion:)":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(topercentage:animationduration:completion:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"abstract":[{"text":"Displays a progress bar and animates it to the provided ","type":"text"},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animateProgressBar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toPercentage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"animationDuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"kind":"text","text":"?)"}],"title":"animateProgressBar(toPercentage:animationDuration:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(toPercentage:animationDuration:completion:)","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","kind":"symbol","type":"topic","title":"StatusBarNotificationLeftViewStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","role":"symbol","navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"title":"StatusBarNotificationProgressBarStyle","abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayProgressBar(percentage:)":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayprogressbar(percentage:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"displayProgressBarWithPercentage:","kind":"identifier"}],"abstract":[{"type":"text","text":"Displays a progress bar at the given "},{"type":"codeVoice","code":"percentage"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"displayProgressBar","kind":"identifier"},{"text":"(","kind":"text"},{"text":"percentage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":")"}],"title":"displayProgressBar(percentage:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(percentage:)","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"navigatorTitle":[{"text":"NotificationPresenterCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenterCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"title":"NotificationPresenterCompletion","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayActivityIndicator(_:)":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayactivityindicator(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"displayActivityIndicator:"}],"abstract":[{"type":"text","text":"Displays an activity indicator as the notifications left view."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"displayActivityIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"displayActivityIndicator(_:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayLeftView(_:)":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayleftview(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"displayLeftView:","kind":"identifier"}],"abstract":[{"type":"text","text":"Displays a view on the left side of the text."},{"type":"text","text":" "},{"text":"The layout is defined by the ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","isActive":true},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayLeftView"},{"text":"(","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"title":"displayLeftView(_:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"animateProgressBarToPercentage:animationDuration:completion:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"animateProgressBarToPercentage:animationDuration:completion:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":[{"generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(percentage:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)"],"title":"Display supplementary views"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animateProgressBarToPercentage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"percentage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationDuration:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animationDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","text":"JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1animateProgressBar(toPercentage:animationDuration:completion:)\/title","value":"animateProgressBarToPercentage:animationDuration:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1animateProgressBar(toPercentage:animationDuration:completion:)\/fragments"},{"op":"replace","value":"JDStatusBarNotificationLeftViewStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"value":"JDStatusBarNotificationProgressBarStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title"},{"value":[{"text":"JDStatusBarNotificationProgressBarStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayProgressBar(percentage:)\/title","value":"displayProgressBarWithPercentage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayProgressBar(percentage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title","op":"replace","value":"JDStatusBarNotificationPresenterCompletionBlock"},{"op":"replace","value":[{"text":"JDStatusBarNotificationPresenterCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayActivityIndicator(_:)\/title","op":"replace","value":"displayActivityIndicator:"},{"value":[{"text":"- ","kind":"text"},{"text":"displayActivityIndicator:","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayActivityIndicator(_:)\/fragments","op":"replace"},{"op":"replace","value":"JDStatusBarNotificationPresenter","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","value":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayLeftView(_:)\/title","op":"replace","value":"displayLeftView:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1displayLeftView(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"displayLeftView:","kind":"identifier"}]}]}]}