{"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)dismissAnimated:","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"dismissAnimated:"}],"title":"dismiss(animated:)","roleHeading":"Instance Method"},"sections":[],"seeAlsoSections":[{"title":"Dismiss a notification","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"animated","content":[{"type":"paragraph","inlineContent":[{"text":"If ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", the notification will be dismissed animated according to the currently"},{"type":"text","text":" "},{"text":"set ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType"},{"type":"text","text":". Otherwise it will be dismissed without animation."}]}]}]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(animated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(animated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:)"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Dismisses any currently displayed notification."}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(animated:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification."}],"navigatorTitle":[{"kind":"identifier","text":"dismissAnimated:"}],"type":"topic","title":"dismiss(animated:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(animated:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationAnimationType","kind":"identifier"}],"abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"type":"topic","title":"StatusBarNotificationAnimationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(afterDelay:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Dismisses any currently displayed notification animated after the provided delay.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dismissAfterDelay:"}],"type":"topic","title":"dismiss(afterDelay:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(afterdelay:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss()":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification immediately using an animation."}],"navigatorTitle":[{"kind":"identifier","text":"dismiss"}],"type":"topic","title":"dismiss()","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss()","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(completion:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Dismisses any currently displayed notification immediately using an animation.","type":"text"}],"navigatorTitle":[{"text":"dismissWithCompletion:","kind":"identifier"}],"type":"topic","title":"dismiss(completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(afterDelay:completion:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"text":"afterDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification animated after the provided delay."}],"navigatorTitle":[{"text":"dismissAfterDelay:completion:","kind":"identifier"}],"type":"topic","title":"dismiss(afterDelay:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(afterdelay:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"dismissAnimated:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"dismissAnimated:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"],"generated":true,"title":"Dismiss a notification"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissAnimated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(animated:)\/title","value":"dismissAnimated:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(animated:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismissAnimated:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"op":"replace","value":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title","value":"JDStatusBarNotificationAnimationType","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationAnimationType"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments"},{"value":"dismissAfterDelay:","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAfterDelay:"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:)\/fragments"},{"op":"replace","value":"dismiss","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss()\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismiss","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(completion:)\/title","value":"dismissWithCompletion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismissWithCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(completion:)\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:completion:)\/title","value":"dismissAfterDelay:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"dismissAfterDelay:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:completion:)\/fragments","op":"replace"}]}]}