{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"type":"text","text":", which gets called once the dismiss animation finishes."}],"type":"paragraph"}]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The animation is determined by the currently set "},{"isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"abstract":[{"type":"text","text":"Dismisses any currently displayed notification immediately using an animation."}],"kind":"symbol","identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(completion:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)dismissWithCompletion:","title":"dismiss(completion:)","modules":[{"name":"JDStatusBarNotification"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(completion:)"]}],"sections":[],"seeAlsoSections":[{"title":"Dismiss a notification","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"],"generated":true}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss()":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismiss","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification immediately using an animation."}],"navigatorTitle":[{"kind":"identifier","text":"dismiss"}],"type":"topic","title":"dismiss()","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss()","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(animated:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification."}],"navigatorTitle":[{"kind":"identifier","text":"dismissAnimated:"}],"type":"topic","title":"dismiss(animated:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(animated:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(afterDelay:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"text":"afterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Dismisses any currently displayed notification animated after the provided delay.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dismissAfterDelay:"}],"type":"topic","title":"dismiss(afterDelay:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(afterdelay:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(afterDelay:completion:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"kind":"text","text":"("},{"text":"afterDelay","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Dismisses any currently displayed notification animated after the provided delay."}],"navigatorTitle":[{"text":"dismissAfterDelay:completion:","kind":"identifier"}],"type":"topic","title":"dismiss(afterDelay:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(afterdelay:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(completion:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dismiss","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?)"}],"abstract":[{"text":"Dismisses any currently displayed notification immediately using an animation.","type":"text"}],"navigatorTitle":[{"text":"dismissWithCompletion:","kind":"identifier"}],"type":"topic","title":"dismiss(completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationAnimationType","kind":"identifier"}],"abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"type":"topic","title":"StatusBarNotificationAnimationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"navigatorTitle":[{"text":"NotificationPresenterCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenterCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"title":"NotificationPresenterCompletion","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"dismissWithCompletion:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"dismissWithCompletion:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":[{"title":"Dismiss a notification","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss()","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(afterDelay:completion:)"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissWithCompletion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","text":"JDStatusBarNotificationPresenterCompletionBlock"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"dismiss","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss()\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismiss"}]},{"value":"dismissAnimated:","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(animated:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(animated:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissAnimated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:)\/title","value":"dismissAfterDelay:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dismissAfterDelay:","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:)\/fragments"},{"value":"dismissAfterDelay:completion:","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:completion:)\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(afterDelay:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAfterDelay:completion:"}],"op":"replace"},{"value":"dismissWithCompletion:","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"dismissWithCompletion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1dismiss(completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}]},{"value":"JDStatusBarNotificationAnimationType","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationAnimationType"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title","op":"replace","value":"JDStatusBarNotificationPresenterCompletionBlock"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments"}]}]}