{"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Present a notification (using a custom view)","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"]}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"text":"?) -> ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"modules":[{"name":"JDStatusBarNotification"}],"externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)presentWithCustomView:styleName:completion:","navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}],"title":"present(customView:style:completion:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"text":"customView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"styleName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"kind":"text","text":"? = nil) -> "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"customView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A custom UIView to display as notification content."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The name of the style. You can use styles previously added using e.g. ","type":"text"},{"isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)","type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"If no style can be found for the given ","type":"text"},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" or it is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the default style will be used."}]}],"name":"styleName"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"type":"text","text":", which gets called once the presentation animation finishes."}]}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The presented UIView for further customization"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"customView"},{"text":" will be layouted correctly according to the selected style & the current device","type":"text"},{"type":"text","text":" "},{"type":"text","text":"state (rotation, status bar visibility, etc.). The background will still be styled & layouted"},{"type":"text","text":" "},{"text":"according to the provided style. If your custom view requires custom touch handling,","type":"text"},{"text":" ","type":"text"},{"text":"make sure to set ","type":"text"},{"type":"codeVoice","code":"style.canTapToHold"},{"type":"text","text":" to "},{"code":"false","type":"codeVoice"},{"type":"text","text":". Otherwise the "},{"type":"codeVoice","code":"customView"},{"type":"text","text":" won’t"},{"text":" ","type":"text"},{"type":"text","text":"receive any touches, as the internal "},{"type":"codeVoice","code":"gestureRecognizer"},{"type":"text","text":" would receive them."}]}]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:style:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:style:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/presentSwiftView(style:viewBuilder:completion:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentSwiftView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"viewBuilder"},{"text":": () -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Present a notification using a custom SwiftUI view."}],"title":"presentSwiftView(style:viewBuilder:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentswiftview(style:viewbuilder:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(styleName:prepare:)":{"navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:prepare:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addStyle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"prepare","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"StatusBarNotificationStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Adds a new custom style. This can be used by referencing it using the "},{"type":"codeVoice","code":"styleName"},{"text":".","type":"text"}],"title":"addStyle(styleName:prepare:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:prepare:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"navigatorTitle":[{"text":"NotificationPresenterCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenterCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"title":"NotificationPresenterCompletion","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:style:completion:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:style:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCustomViewSizingController":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresentercustomviewsizingcontroller","kind":"symbol","title":"NotificationPresenterCustomViewSizingController","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","navigatorTitle":[{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"abstract":[{"text":"A protocol for a custom controller, which controls the size of a presented custom view.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:sizingController:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:sizingController:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizingController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController","text":"NotificationPresenterCustomViewSizingController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:sizingController:style:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:sizingcontroller:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"presentWithCustomView:styleName:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentWithCustomView:styleName:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"],"generated":true,"title":"Present a notification (using a custom view)"}]},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"presentWithCustomView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"text":"customView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"styleName:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"styleName"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"addStyleNamed:prepare:","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addStyleNamed:prepare:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title","value":"JDStatusBarNotificationPresenterCompletionBlock","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/title","op":"replace","value":"presentWithCustomView:styleName:completion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/fragments"},{"value":"JDStatusBarNotificationPresenterCustomViewSizingController","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCustomViewSizingController"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/fragments"},{"value":"presentWithCustomView:sizingController:styleName:completion:","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"presentWithCustomView:sizingController:styleName:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}