{"seeAlsoSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"],"title":"Present a notification (using a custom view)","generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizingController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","text":"NotificationPresenterCustomViewSizingController","preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController"},{"kind":"text","text":"?, "},{"text":"style","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"styleName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","kind":"typeIdentifier","text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"? = nil) -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"customView","content":[{"inlineContent":[{"text":"A custom UIView to display as notification content.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional controller conforming to "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"},{"type":"text","text":", which controls the size of a presented custom view."}]}],"name":"sizingController"},{"name":"styleName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The name of the style. You can use styles previously added using e.g. "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If no style can be found for the given "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" or it is "},{"type":"codeVoice","code":"nil"},{"text":", the default style will be used.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"type":"text","text":", which gets called once the presentation animation finishes."}]}],"name":"completion"}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"The presented UIView for further customization","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"customView"},{"type":"text","text":" will be layouted correctly according to the selected style & the current device"},{"type":"text","text":" "},{"text":"state (rotation, status bar visibility, etc.). The background will still be styled & layouted","type":"text"},{"type":"text","text":" "},{"text":"according to the provided style. If your custom view requires custom touch handling,","type":"text"},{"type":"text","text":" "},{"text":"make sure to set ","type":"text"},{"type":"codeVoice","code":"style.canTapToHold"},{"type":"text","text":" to "},{"code":"false","type":"codeVoice"},{"text":". Otherwise the ","type":"text"},{"code":"customView","type":"codeVoice"},{"text":" won’t","type":"text"},{"text":" ","type":"text"},{"text":"receive any touches, as the internal ","type":"text"},{"type":"codeVoice","code":"gestureRecognizer"},{"text":" would receive them.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"sections":[],"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"sizingController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"title":"present(customView:sizingController:style:completion:)","navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:sizingController:styleName:completion:"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)presentWithCustomView:sizingController:styleName:completion:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:sizingcontroller:style:completion:)"]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:sizingcontroller:style:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:style:completion:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:style:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCustomViewSizingController":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresentercustomviewsizingcontroller","kind":"symbol","title":"NotificationPresenterCustomViewSizingController","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","navigatorTitle":[{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"abstract":[{"text":"A protocol for a custom controller, which controls the size of a presented custom view.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(styleName:prepare:)":{"navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:prepare:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addStyle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"prepare","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"StatusBarNotificationStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Adds a new custom style. This can be used by referencing it using the "},{"type":"codeVoice","code":"styleName"},{"text":".","type":"text"}],"title":"addStyle(styleName:prepare:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:prepare:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"navigatorTitle":[{"text":"NotificationPresenterCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenterCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"title":"NotificationPresenterCompletion","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:sizingController:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:sizingController:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizingController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController","text":"NotificationPresenterCustomViewSizingController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:sizingController:style:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:sizingcontroller:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/presentSwiftView(style:viewBuilder:completion:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentSwiftView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"viewBuilder"},{"text":": () -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Present a notification using a custom SwiftUI view."}],"title":"presentSwiftView(style:viewBuilder:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentswiftview(style:viewbuilder:completion:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"presentWithCustomView:sizingController:styleName:completion:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithCustomView:sizingController:styleName:completion:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Present a notification (using a custom view)","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" *) ","kind":"text"},{"text":"presentWithCustomView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"customView"},{"text":" ","kind":"text"},{"text":"sizingController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<JDStatusBarNotificationPresenterCustomViewSizingController>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)JDStatusBarNotificationPresenterCustomViewSizingController"},{"kind":"text","text":" *) "},{"text":"sizingController","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"styleName:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"styleName"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"JDStatusBarNotificationPresenterCompletionBlock"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/title","op":"replace","value":"presentWithCustomView:styleName:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"presentWithCustomView:styleName:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/title","value":"JDStatusBarNotificationPresenterCustomViewSizingController"},{"op":"replace","value":[{"text":"JDStatusBarNotificationPresenterCustomViewSizingController","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/title","value":"addStyleNamed:prepare:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"addStyleNamed:prepare:","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title","op":"replace","value":"JDStatusBarNotificationPresenterCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCompletionBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/title","value":"presentWithCustomView:sizingController:styleName:completion:"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentWithCustomView:sizingController:styleName:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"JDStatusBarNotificationPresenter","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}