{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:dismissAfterDelay:includedStyle:)"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"metadata":{"role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismissAfterDelay","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"includedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"text":") -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"title":"present(text:dismissAfterDelay:includedStyle:)","navigatorTitle":[{"kind":"identifier","text":"presentWithText:dismissAfterDelay:includedStyle:"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)presentWithText:dismissAfterDelay:includedStyle:"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"dismissAfterDelay","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delay"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"kind":"text","text":", "},{"text":"includedStyle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"text","content":[{"inlineContent":[{"text":"The text to display","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The delay in seconds, before the notification should be dismissed.","type":"text"}]}],"name":"delay"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An existing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"}]}],"name":"includedStyle"}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The presented UIView for further customization"}]}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"The notification will dismiss after the given ","type":"text"},{"code":"delay","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)"],"title":"Present a notification (using an included style)"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:dismissafterdelay:includedstyle:)"]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:dismissafterdelay:includedstyle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"role":"symbol","title":"IncludedStatusBarNotificationStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"notification without creating your own custom style."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:dismissAfterDelay:includedStyle:)":{"kind":"symbol","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"code":"includedStyle","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"presentWithText:dismissAfterDelay:includedStyle:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:dismissafterdelay:includedstyle:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:dismissAfterDelay:includedStyle:)","title":"present(text:dismissAfterDelay:includedStyle:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"dismissAfterDelay","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(title:subtitle:includedStyle:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Present a notification using an existing "},{"code":"includedStyle","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"presentWithTitle:subtitle:includedStyle:completion:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(title:subtitle:includedstyle:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)","title":"present(title:subtitle:includedStyle:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"subtitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"includedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"typeIdentifier","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:includedStyle:)":{"kind":"symbol","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"code":"includedStyle","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"presentWithText:includedStyle:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:)","role":"symbol","type":"topic","title":"present(text:includedStyle:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"includedStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:includedStyle:completion:)":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"includedStyle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:completion:)","navigatorTitle":[{"text":"presentWithText:includedStyle:completion:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"present(text:includedStyle:completion:)","abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"text":".","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"presentWithText:dismissAfterDelay:includedStyle:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"presentWithText:dismissAfterDelay:includedStyle:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Present a notification (using an included style)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)"],"generated":true}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"presentWithText:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"text":"dismissAfterDelay:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"internalParam","text":"delay"},{"text":" ","kind":"text"},{"kind":"identifier","text":"includedStyle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"JDStatusBarNotificationIncludedStyle","kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"},{"text":") ","kind":"text"},{"text":"includedStyle","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"JDStatusBarNotificationIncludedStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyle"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:dismissAfterDelay:includedStyle:)\/title","value":"presentWithText:dismissAfterDelay:includedStyle:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:dismissAfterDelay:includedStyle:"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:dismissAfterDelay:includedStyle:)\/fragments"},{"value":"JDStatusBarNotificationPresenter","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","op":"replace"},{"op":"replace","value":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(title:subtitle:includedStyle:completion:)\/title","value":"presentWithTitle:subtitle:includedStyle:completion:","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(title:subtitle:includedStyle:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithTitle:subtitle:includedStyle:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:)\/title","op":"replace","value":"presentWithText:includedStyle:"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentWithText:includedStyle:","kind":"identifier"}]},{"value":"presentWithText:includedStyle:completion:","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}