{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The presented UIView for further customization"}]}]},{"kind":"parameters","parameters":[{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text to display"}]}]},{"name":"includedStyle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An existing "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"type":"text","text":", which gets called once the presentation animation finishes."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"title":"present(text:includedStyle:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)presentWithText:includedStyle:completion:","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}]},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"seeAlsoSections":[{"title":"Present a notification (using an included style)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:dismissAfterDelay:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"],"generated":true}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:includedStyle:)":{"role":"symbol","title":"present(text:includedStyle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentWithText:includedStyle:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"role":"symbol","title":"IncludedStatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"abstract":[],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"role":"symbol","title":"NotificationPresenter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationPresenter"}],"abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"type":"text","text":" "},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(title:subtitle:includedStyle:completion:)":{"role":"symbol","title":"present(title:subtitle:includedStyle:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subtitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentWithTitle:subtitle:includedStyle:completion:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(title:subtitle:includedstyle:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:dismissAfterDelay:includedStyle:)":{"role":"symbol","title":"present(text:dismissAfterDelay:includedStyle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAfterDelay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:dismissAfterDelay:includedStyle:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentWithText:dismissAfterDelay:includedStyle:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:dismissafterdelay:includedstyle:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(text:includedStyle:completion:)":{"role":"symbol","title":"present(text:includedStyle:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"present"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"includedStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"Present a notification using an existing "},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(text:includedstyle:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"role":"symbol","title":"NotificationPresenterCompletion","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationPresenterCompletion"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenterCompletion"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentWithText:includedStyle:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Present a notification (using an included style)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(title:subtitle:includedStyle:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(text:dismissAfterDelay:includedStyle:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"presentWithText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"includedStyle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"JDStatusBarNotificationIncludedStyle"},{"kind":"text","text":")"},{"kind":"internalParam","text":"includedStyle"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:)\/title","value":"presentWithText:includedStyle:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:includedStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","value":"JDStatusBarNotificationIncludedStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","value":"JDStatusBarNotificationPresenter"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(title:subtitle:includedStyle:completion:)\/title","value":"presentWithTitle:subtitle:includedStyle:completion:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(title:subtitle:includedStyle:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithTitle:subtitle:includedStyle:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:dismissAfterDelay:includedStyle:)\/title","value":"presentWithText:dismissAfterDelay:includedStyle:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:dismissAfterDelay:includedStyle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:dismissAfterDelay:includedStyle:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:completion:)\/title","value":"presentWithText:includedStyle:completion:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(text:includedStyle:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title","value":"JDStatusBarNotificationPresenterCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCompletionBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}