{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"JDStatusBarNotification"}],"symbolKind":"method","role":"symbol","extendedModule":"JDStatusBarNotification","externalID":"s:So32JDStatusBarNotificationPresenterC0abC0E16presentSwiftView5style11viewBuilder10completionySSSg_xyXEyABcSgt0F2UI0G0RzlF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"presentSwiftView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"viewBuilder","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"View","preciseIdentifier":"s:7SwiftUI4ViewP"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"text":"?)","kind":"text"}],"title":"presentSwiftView(style:viewBuilder:completion:)"},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"]]},"kind":"symbol","abstract":[{"type":"text","text":"Present a notification using a custom SwiftUI view."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentswiftview(style:viewbuilder:completion:)"]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"Present a notification (using a custom view)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentSwiftView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:7SwiftUI11ViewBuilderV","text":"ViewBuilder","kind":"attribute"},{"text":" ","kind":"text"},{"text":"viewBuilder","kind":"externalParam"},{"kind":"text","text":": () -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"text":"View","preciseIdentifier":"s:7SwiftUI4ViewP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"The name of the style. You can use styles previously added using e.g. ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)","isActive":true},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If no style can be found for the given "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" or it is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":", the default style will be used."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A ViewBuilder closure to build your custom SwiftUI view."}],"type":"paragraph"}],"name":"viewBuilder"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion"},{"type":"text","text":", which gets called once the presentation animation finishes."}]}]}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(styleName:prepare:)":{"navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:prepare:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addStyle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"styleName"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"prepare","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"StatusBarNotificationStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle"},{"kind":"text","text":") -> "},{"text":"StatusBarNotificationStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationStyle","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[{"type":"text","text":"Adds a new custom style. This can be used by referencing it using the "},{"type":"codeVoice","code":"styleName"},{"text":".","type":"text"}],"title":"addStyle(styleName:prepare:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(stylename:prepare:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(styleName:prepare:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/presentSwiftView(style:viewBuilder:completion:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentSwiftView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"viewBuilder"},{"text":": () -> ","kind":"text"},{"text":"some","kind":"keyword"},{"kind":"text","text":" "},{"text":"View","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","text":"NotificationPresenterCompletion"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Present a notification using a custom SwiftUI view."}],"title":"presentSwiftView(style:viewBuilder:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(style:viewBuilder:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentswiftview(style:viewbuilder:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCompletion":{"navigatorTitle":[{"text":"NotificationPresenterCompletion","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenterCompletion","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"title":"NotificationPresenterCompletion","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCompletion","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercompletion"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCustomViewSizingController":{"url":"\/documentation\/jdstatusbarnotification\/notificationpresentercustomviewsizingcontroller","kind":"symbol","title":"NotificationPresenterCustomViewSizingController","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","navigatorTitle":[{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"abstract":[{"text":"A protocol for a custom controller, which controls the size of a presented custom view.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenter","kind":"identifier"}],"title":"NotificationPresenter","navigatorTitle":[{"text":"NotificationPresenter","kind":"identifier"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","role":"symbol","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:sizingController:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:sizingController:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizingController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController","text":"NotificationPresenterCustomViewSizingController","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","kind":"typeIdentifier","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:sizingController:style:completion:)","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:sizingController:style:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:sizingcontroller:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(customView:style:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"text":"customView","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NotificationPresenterCompletion","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"abstract":[{"type":"text","text":"Present a notification using a custom subview."}],"title":"present(customView:style:completion:)","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(customview:style:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(customView:style:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/title","value":"addStyleNamed:prepare:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:prepare:"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1addStyle(styleName:prepare:)\/fragments","op":"replace"},{"value":"JDStatusBarNotificationPresenterCompletionBlock","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCompletion\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCompletionBlock"}]},{"op":"replace","value":"JDStatusBarNotificationPresenterCustomViewSizingController","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/fragments","value":[{"text":"JDStatusBarNotificationPresenterCustomViewSizingController","kind":"identifier"}]},{"value":"JDStatusBarNotificationPresenter","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/title","value":"presentWithCustomView:sizingController:styleName:completion:"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:sizingController:style:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentWithCustomView:sizingController:styleName:completion:","kind":"identifier"}]},{"op":"replace","value":"presentWithCustomView:styleName:completion:","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenter~1present(customView:style:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithCustomView:styleName:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}