{"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"center"}],"symbolKind":"case","role":"symbol","title":"StatusBarNotificationProgressBarPosition.center","externalID":"c:@E@JDStatusBarNotificationProgressBarPosition@JDStatusBarNotificationProgressBarPositionCenter","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarPositionCenter"}],"roleHeading":"Case","modules":[{"name":"JDStatusBarNotification"}]},"abstract":[{"type":"text","text":"The progress bar will be at the center of the notification content."}],"sections":[],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition\/center"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition\/center"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition\/center"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"center","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"]]},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"title":"StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"title":"StatusBarNotificationProgressBarPosition","kind":"symbol","abstract":[{"text":"Defines the position of the progress bar, when used.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition/center":{"navigatorTitle":[{"text":"JDStatusBarNotificationProgressBarPositionCenter","kind":"identifier"}],"role":"symbol","title":"StatusBarNotificationProgressBarPosition.center","type":"topic","abstract":[{"type":"text","text":"The progress bar will be at the center of the notification content."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition\/center","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition\/center","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"center"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"JDStatusBarNotificationProgressBarPositionCenter"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"JDStatusBarNotificationProgressBarPositionCenter","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarPositionCenter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/title","value":"JDStatusBarNotificationProgressBarPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/fragments","value":[{"text":"JDStatusBarNotificationProgressBarPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition~1center\/title","value":"JDStatusBarNotificationProgressBarPositionCenter"},{"op":"replace","value":[{"text":"JDStatusBarNotificationProgressBarPositionCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition~1center\/fragments"}]}]}