{"topicSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition\/!=(_:_:)"],"title":"Operators","generated":true}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"title":"Equatable Implementations","role":"collectionGroup"},"sections":[],"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition\/Equatable-Implementations"},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition/!=(_:_:)":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition\/!=(_:_:)","abstract":[],"kind":"symbol","type":"topic","title":"!=(_:_:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"title":"StatusBarNotificationProgressBarPosition","kind":"symbol","abstract":[{"text":"Defines the position of the progress bar, when used.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"title":"StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/title","op":"replace","value":"JDStatusBarNotificationProgressBarPosition"},{"value":[{"text":"JDStatusBarNotificationProgressBarPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/fragments","op":"replace"},{"value":"JDStatusBarNotificationStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}