{"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:basedOnStyle:prepare:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"addStyleNamed:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"styleName"},{"kind":"text","text":" "},{"text":"basedOnStyle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JDStatusBarNotificationIncludedStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"},{"kind":"text","text":") "},{"text":"basedOnStyle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"prepare:"},{"kind":"text","text":"("},{"text":"JDStatusBarNotificationStyle *(^)(JDStatusBarNotificationStyle *)","preciseIdentifier":"c:BF*$objc(cs)JDStatusBarNotificationStyle(#S2_)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"prepareBlock","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"styleName","content":[{"inlineContent":[{"text":"The styleName which will later be used to reference the added style.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","isActive":true},{"text":", which you want to base your style on.","type":"text"}],"type":"paragraph"}],"name":"basedOnStyle"},{"name":"prepareBlock","content":[{"inlineContent":[{"text":"Provides an ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","isActive":true,"type":"reference"},{"text":" instance based on the provided ","type":"text"},{"type":"codeVoice","code":"basedOnStyle"},{"text":" for further customization.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns the "},{"code":"styleName","type":"codeVoice"},{"text":", so that this call can be used directly within a presentation call.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The added style can be used in future presentations by utilizing the same "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" in e.g. "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:","isActive":true,"type":"reference"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"If a style with the same name already exists, it will be replaced.","type":"text"}]}]}],"metadata":{"externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)addStyleNamed:basedOnStyle:prepare:","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}],"modules":[{"name":"JDStatusBarNotification"}],"role":"symbol","title":"addStyleNamed:basedOnStyle:prepare:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"generated":true,"title":"Customize the style (Appearance & Behavior)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateDefaultStyle:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:prepare:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterPrepareStyleBlock"]}],"abstract":[{"text":"Adds a new named style based on an included style.","type":"text"},{"text":" ","type":"text"},{"text":"This can later be used by referencing it using the ","type":"text"},{"code":"styleName","type":"codeVoice"},{"type":"text","text":" - or by using the return value directly."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/addstylenamed:basedonstyle:prepare:"]}],"sections":[],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","kind":"symbol","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"notification without creating your own custom style."}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"type":"topic","title":"IncludedStatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:customStyle:":{"fragments":[{"kind":"text","text":"- "},{"text":"presentWithText:customStyle:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:","abstract":[{"text":"Present a notification using a specified ","type":"text"},{"code":"customStyle","type":"codeVoice"},{"text":".","type":"text"}],"title":"presentWithText:customStyle:","navigatorTitle":[{"text":"presentWithText:customStyle:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:customstyle:","kind":"symbol","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/addStyleNamed:basedOnStyle:prepare:":{"title":"addStyleNamed:basedOnStyle:prepare:","type":"topic","abstract":[{"text":"Adds a new named style based on an included style.","type":"text"},{"text":" ","type":"text"},{"text":"This can later be used by referencing it using the ","type":"text"},{"code":"styleName","type":"codeVoice"},{"type":"text","text":" - or by using the return value directly."}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:basedOnStyle:prepare:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}],"navigatorTitle":[{"text":"addStyleNamed:basedOnStyle:prepare:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/addstylenamed:basedonstyle:prepare:","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/updateDefaultStyle:":{"title":"updateDefaultStyle:","type":"topic","abstract":[{"text":"Defines a new default style.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The new style will be used in all future presentations that have no specific style specified."}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateDefaultStyle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateDefaultStyle:"}],"navigatorTitle":[{"text":"updateDefaultStyle:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/updatedefaultstyle:","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","kind":"symbol","abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter","fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"type":"topic","title":"JDStatusBarNotificationPresenter","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/addStyleNamed:prepare:":{"title":"addStyleNamed:prepare:","type":"topic","abstract":[{"type":"text","text":"Adds a new named style."},{"text":" ","type":"text"},{"type":"text","text":"This can later be used by referencing it using the "},{"code":"styleName","type":"codeVoice"},{"type":"text","text":" - or by using the return value directly."}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:prepare:","fragments":[{"kind":"text","text":"- "},{"text":"addStyleNamed:prepare:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:prepare:"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/addstylenamed:prepare:","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenterPrepareStyleBlock":{"title":"JDStatusBarNotificationPresenterPrepareStyleBlock","type":"topic","abstract":[{"type":"text","text":"Creates a modified copy of an existing "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},{"type":"text","text":" instance."}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterPrepareStyleBlock","fragments":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterPrepareStyleBlock"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenterpreparestyleblock","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"JDStatusBarNotificationIncludedStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationIncludedStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle","op":"replace"},{"value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}