{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:"},"metadata":{"externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)animateProgressBarToPercentage:animationDuration:completion:","navigatorTitle":[{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"fragments":[{"text":"- ","kind":"text"},{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"title":"animateProgressBarToPercentage:animationDuration:completion:","roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter"]]},"abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}],"seeAlsoSections":[{"generated":true,"title":"Display supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:"]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/animateprogressbartopercentage:animationduration:completion:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"animateProgressBarToPercentage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"percentage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animationDuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"text":"JDStatusBarNotificationPresenterCompletionBlock","preciseIdentifier":"c:JDStatusBarNotificationPresenter.h@T@JDStatusBarNotificationPresenterCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterCompletionBlock"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Relative progress from 0.0 to 1.0","type":"text"}],"type":"paragraph"}],"name":"percentage"},{"name":"animationDuration","content":[{"type":"paragraph","inlineContent":[{"text":"The duration of the animation from the current percentage to the provided percentage.","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterCompletionBlock","isActive":true},{"text":", which gets called once the progress bar animation finishes.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Animates the progress bar from the currently set "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":" to the provided "},{"code":"percentage","type":"codeVoice"},{"type":"text","text":" using the provided "},{"type":"codeVoice","code":"animationDuration"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The progress bar will be styled according to the current "},{"isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","type":"reference"},{"text":".","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","sections":[],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayLeftView:":{"navigatorTitle":[{"kind":"identifier","text":"displayLeftView:"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:","kind":"symbol","abstract":[{"text":"Displays a view on the left side of the text.","type":"text"},{"type":"text","text":" "},{"text":"The layout is defined by the ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","isActive":true,"type":"reference"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayleftview:","type":"topic","title":"displayLeftView:","fragments":[{"text":"- ","kind":"text"},{"text":"displayLeftView:","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayProgressBarWithPercentage:":{"navigatorTitle":[{"text":"displayProgressBarWithPercentage:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","kind":"symbol","abstract":[{"type":"text","text":"Displays a progress bar at the given "},{"code":"percentage","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayprogressbarwithpercentage:","type":"topic","title":"displayProgressBarWithPercentage:","fragments":[{"text":"- ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/animateProgressBarToPercentage:animationDuration:completion:":{"navigatorTitle":[{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:","kind":"symbol","abstract":[{"text":"Displays a progress bar and animates it to the provided ","type":"text"},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/animateprogressbartopercentage:animationduration:completion:","type":"topic","title":"animateProgressBarToPercentage:animationDuration:completion:","fragments":[{"kind":"text","text":"- "},{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the appeareance of the progress bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"title":"StatusBarNotificationProgressBarStyle","type":"topic","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayActivityIndicator:":{"navigatorTitle":[{"text":"displayActivityIndicator:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","kind":"symbol","abstract":[{"text":"Displays an activity indicator as the notifications left view.","type":"text"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayactivityindicator:","type":"topic","title":"displayActivityIndicator:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"displayActivityIndicator:"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"title":"StatusBarNotificationLeftViewStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","kind":"symbol","abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter","fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"type":"topic","title":"JDStatusBarNotificationPresenter","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenterCompletionBlock":{"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresentercompletionblock","type":"topic","title":"JDStatusBarNotificationPresenterCompletionBlock","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterCompletionBlock","role":"symbol","fragments":[{"text":"JDStatusBarNotificationPresenterCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JDStatusBarNotificationProgressBarStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarStyle"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments"},{"op":"replace","value":"JDStatusBarNotificationLeftViewStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"text":"JDStatusBarNotificationLeftViewStyle","kind":"identifier"}]}]}]}