{"seeAlsoSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:"],"generated":true,"title":"Display supplementary views"}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"displayProgressBarWithPercentage:","fragments":[{"text":"- ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"}],"role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"symbolKind":"method","externalID":"c:objc(cs)JDStatusBarNotificationPresenter(im)displayProgressBarWithPercentage:","navigatorTitle":[{"kind":"identifier","text":"displayProgressBarWithPercentage:"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayprogressbarwithpercentage:"]}],"abstract":[{"text":"Displays a progress bar at the given ","type":"text"},{"code":"percentage","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"percentage","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},{"parameters":[{"name":"percentage","content":[{"inlineContent":[{"type":"text","text":"The percentage in a range from 0.0 to 1.0"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Displays the given percentage immediately without animation.","type":"text"},{"text":" ","type":"text"},{"text":"The progress bar will be styled according to the current ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","isActive":true},{"type":"text","text":"."}]}]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayActivityIndicator:":{"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayactivityindicator:","role":"symbol","title":"displayActivityIndicator:","navigatorTitle":[{"kind":"identifier","text":"displayActivityIndicator:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"displayActivityIndicator:"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","type":"topic","abstract":[{"type":"text","text":"Displays an activity indicator as the notifications left view."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayProgressBarWithPercentage:":{"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayprogressbarwithpercentage:","role":"symbol","title":"displayProgressBarWithPercentage:","navigatorTitle":[{"kind":"identifier","text":"displayProgressBarWithPercentage:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","type":"topic","abstract":[{"type":"text","text":"Displays a progress bar at the given "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","title":"StatusBarNotificationProgressBarStyle","abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayLeftView:":{"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayleftview:","kind":"symbol","role":"symbol","title":"displayLeftView:","navigatorTitle":[{"kind":"identifier","text":"displayLeftView:"}],"fragments":[{"kind":"text","text":"- "},{"text":"displayLeftView:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:","abstract":[{"type":"text","text":"Displays a view on the left side of the text."},{"type":"text","text":" "},{"type":"text","text":"The layout is defined by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"},{"type":"text","text":"."}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter":{"fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"text":" ","type":"text"},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"text":" ","type":"text"},{"text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"title":"JDStatusBarNotificationPresenter","kind":"symbol","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/animateProgressBarToPercentage:animationDuration:completion:":{"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/animateprogressbartopercentage:animationduration:completion:","kind":"symbol","role":"symbol","title":"animateProgressBarToPercentage:animationDuration:completion:","navigatorTitle":[{"kind":"identifier","text":"animateProgressBarToPercentage:animationDuration:completion:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:","abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"title":"StatusBarNotificationLeftViewStyle","kind":"symbol","navigatorTitle":[{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","value":"JDStatusBarNotificationProgressBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments","value":[{"text":"JDStatusBarNotificationProgressBarStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","op":"replace","value":"JDStatusBarNotificationLeftViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]}]}]}