{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"]}],"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"roleHeading":"Class","externalID":"c:objc(cs)JDStatusBarNotificationPresenter","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationPresenter"}],"symbolKind":"class","fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"title":"JDStatusBarNotificationPresenter","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter"]}],"abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"type":"text","text":" "},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"type":"text","text":" "},{"text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a","type":"text"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JDStatusBarNotificationPresenter","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"To customize the appearance, see the "},{"type":"emphasis","inlineContent":[{"type":"text","text":"Customize the style"}]},{"type":"text","text":" section. To see all customization"},{"type":"text","text":" "},{"text":"options, see the ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","isActive":true},{"type":"text","text":" documentation."}],"type":"paragraph"},{"inlineContent":[{"text":"While a notification is displayed, a separate window is presented on top of your application","type":"text"},{"type":"text","text":" "},{"type":"text","text":"window. Upon dismissal this window, its view controller and all its views are removed from"},{"type":"text","text":" "},{"text":"memory. The presenter class itself is a singleton which will stay in memory for the lifetime of","type":"text"},{"type":"text","text":" "},{"text":"your application once it was created. The default ","type":"text"},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","isActive":true},{"type":"text","text":" and any styles"},{"type":"text","text":" "},{"text":"added by the user also stay in memory permanently.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","interfaceLanguage":"occ"},"topicSections":[{"title":"Retrieve the presenter","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/sharedPresenter"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterCompletionBlock"],"title":"Present a notification"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:customStyle:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:customStyle:"],"title":"Present a notification (using a custom style)"},{"title":"Present a notification (using an included style)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:includedStyle:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:includedStyle:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:includedStyle:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:includedStyle:"]},{"title":"Present a notification (using a custom view)","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithCustomView:styleName:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithCustomView:sizingController:styleName:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismiss","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissWithCompletion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAnimated:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAfterDelay:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAfterDelay:completion:"],"title":"Dismiss a notification"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateDefaultStyle:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:prepare:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:basedOnStyle:prepare:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterPrepareStyleBlock"],"title":"Customize the style (Appearance & Behavior)"},{"title":"Display supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/isVisible","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateText:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateSubtitle:","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/setWindowScene:"],"title":"Additional Presenter APIs"},{"title":"Instance Methods","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAnimated:afterDelay:completion:"]}],"kind":"symbol","references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithTitle:subtitle:customStyle:completion:":{"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithTitle:subtitle:customStyle:completion:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"presentWithTitle:subtitle:customStyle:completion:"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:customStyle:completion:","kind":"symbol","title":"presentWithTitle:subtitle:customStyle:completion:","role":"symbol","abstract":[{"type":"text","text":"Present a notification using a specified "},{"code":"customStyle","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtitle:subtitle:customstyle:completion:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/addStyleNamed:prepare:":{"fragments":[{"text":"- ","kind":"text"},{"text":"addStyleNamed:prepare:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/addstylenamed:prepare:","navigatorTitle":[{"text":"addStyleNamed:prepare:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:prepare:","abstract":[{"type":"text","text":"Adds a new named style."},{"type":"text","text":" "},{"type":"text","text":"This can later be used by referencing it using the "},{"type":"codeVoice","code":"styleName"},{"type":"text","text":" - or by using the return value directly."}],"title":"addStyleNamed:prepare:","type":"topic","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismissAnimated:afterDelay:completion:":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAnimated:afterDelay:completion:","fragments":[{"text":"- ","kind":"text"},{"text":"dismissAnimated:afterDelay:completion:","kind":"identifier"}],"type":"topic","role":"symbol","title":"dismissAnimated:afterDelay:completion:","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismissanimated:afterdelay:completion:","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"dismissAnimated:afterDelay:completion:","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/isVisible":{"fragments":[{"kind":"text","text":"- "},{"text":"isVisible","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Let’s you check if a notification is currently displayed."}],"role":"symbol","type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/isVisible","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/isvisible","title":"isVisible","navigatorTitle":[{"kind":"identifier","text":"isVisible"}]},"doc://calimarkus.JDStatusBarNotification/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject","title":"NSObject"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/updateDefaultStyle:":{"type":"topic","navigatorTitle":[{"text":"updateDefaultStyle:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateDefaultStyle:","abstract":[{"text":"Defines a new default style.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The new style will be used in all future presentations that have no specific style specified."}],"title":"updateDefaultStyle:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"updateDefaultStyle:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/updatedefaultstyle:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:customStyle:":{"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:customstyle:","navigatorTitle":[{"kind":"identifier","text":"presentWithText:customStyle:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:customStyle:"}],"title":"presentWithText:customStyle:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:","abstract":[{"text":"Present a notification using a specified ","type":"text"},{"code":"customStyle","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithTitle:subtitle:completion:":{"title":"presentWithTitle:subtitle:completion:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:completion:","abstract":[{"text":"Present a notification using the current default style.","type":"text"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtitle:subtitle:completion:","navigatorTitle":[{"kind":"identifier","text":"presentWithTitle:subtitle:completion:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithTitle:subtitle:completion:"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:includedStyle:completion:":{"type":"topic","abstract":[{"type":"text","text":"Present a notification using an existing "},{"code":"includedStyle","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}],"navigatorTitle":[{"kind":"identifier","text":"presentWithText:includedStyle:completion:"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:includedstyle:completion:","title":"presentWithText:includedStyle:completion:","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:includedStyle:completion:","role":"symbol","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismissAnimated:":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAnimated:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dismissAnimated:"}],"navigatorTitle":[{"text":"dismissAnimated:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismissanimated:","type":"topic","abstract":[{"text":"Dismisses any currently displayed notification.","type":"text"}],"kind":"symbol","title":"dismissAnimated:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:customStyle:completion:":{"fragments":[{"kind":"text","text":"- "},{"text":"presentWithText:customStyle:completion:","kind":"identifier"}],"navigatorTitle":[{"text":"presentWithText:customStyle:completion:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:customStyle:completion:","kind":"symbol","title":"presentWithText:customStyle:completion:","role":"symbol","abstract":[{"type":"text","text":"Present a notification using a specified "},{"code":"customStyle","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:customstyle:completion:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"text":"A Style defines the appeareance of a notification.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter":{"fragments":[{"text":"JDStatusBarNotificationPresenter","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter","abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"text":" ","type":"text"},{"type":"text","text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch"},{"text":" ","type":"text"},{"text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"title":"JDStatusBarNotificationPresenter","kind":"symbol","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayActivityIndicator:":{"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayactivityindicator:","role":"symbol","title":"displayActivityIndicator:","navigatorTitle":[{"kind":"identifier","text":"displayActivityIndicator:"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"displayActivityIndicator:"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayActivityIndicator:","type":"topic","abstract":[{"type":"text","text":"Displays an activity indicator as the notifications left view."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismiss":{"type":"topic","title":"dismiss","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismiss","abstract":[{"type":"text","text":"Dismisses any currently displayed notification immediately using an animation."}],"fragments":[{"text":"- ","kind":"text"},{"text":"dismiss","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismiss","navigatorTitle":[{"text":"dismiss","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:includedStyle:":{"type":"topic","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"type":"codeVoice","code":"includedStyle"},{"text":".","type":"text"}],"fragments":[{"kind":"text","text":"- "},{"text":"presentWithText:includedStyle:","kind":"identifier"}],"navigatorTitle":[{"text":"presentWithText:includedStyle:","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:includedstyle:","title":"presentWithText:includedStyle:","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:includedStyle:","role":"symbol","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismissAfterDelay:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"dismissAfterDelay:","kind":"identifier"}],"navigatorTitle":[{"text":"dismissAfterDelay:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAfterDelay:","type":"topic","abstract":[{"text":"Dismisses any currently displayed notification animated after the provided delay.","type":"text"}],"title":"dismissAfterDelay:","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismissafterdelay:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"type":"topic","title":"IncludedStatusBarNotificationStyle","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"notification without creating your own custom style."}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismissAfterDelay:completion:":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"dismissAfterDelay:completion:","kind":"identifier"}],"kind":"symbol","title":"dismissAfterDelay:completion:","navigatorTitle":[{"text":"dismissAfterDelay:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissAfterDelay:completion:","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismissafterdelay:completion:","abstract":[{"type":"text","text":"Dismisses any currently displayed notification animated after the provided delay."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:":{"title":"presentWithText:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:","abstract":[{"text":"Present a notification using the current default style.","type":"text"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:","navigatorTitle":[{"text":"presentWithText:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithText:"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:dismissAfterDelay:":{"title":"presentWithText:dismissAfterDelay:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:","type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:dismissafterdelay:","abstract":[{"text":"Present a notification using the current default style.","type":"text"}],"navigatorTitle":[{"text":"presentWithText:dismissAfterDelay:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentWithText:dismissAfterDelay:"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCustomViewSizingController":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercustomviewsizingcontroller","navigatorTitle":[{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","abstract":[{"text":"A protocol for a custom controller, which controls the size of a presented custom view.","type":"text"}],"title":"NotificationPresenterCustomViewSizingController","type":"topic","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayProgressBarWithPercentage:":{"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayprogressbarwithpercentage:","role":"symbol","title":"displayProgressBarWithPercentage:","navigatorTitle":[{"kind":"identifier","text":"displayProgressBarWithPercentage:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"displayProgressBarWithPercentage:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayProgressBarWithPercentage:","type":"topic","abstract":[{"type":"text","text":"Displays a progress bar at the given "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithTitle:subtitle:includedStyle:completion:":{"type":"topic","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"type":"codeVoice","code":"includedStyle"},{"type":"text","text":"."}],"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithTitle:subtitle:includedStyle:completion:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"presentWithTitle:subtitle:includedStyle:completion:"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtitle:subtitle:includedstyle:completion:","title":"presentWithTitle:subtitle:includedStyle:completion:","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithTitle:subtitle:includedStyle:completion:","role":"symbol","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/updateText:":{"fragments":[{"kind":"text","text":"- "},{"text":"updateText:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Updates the text of an existing notification without animation."}],"role":"symbol","type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateText:","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/updatetext:","title":"updateText:","navigatorTitle":[{"kind":"identifier","text":"updateText:"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/displayLeftView:":{"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/displayleftview:","kind":"symbol","role":"symbol","title":"displayLeftView:","navigatorTitle":[{"kind":"identifier","text":"displayLeftView:"}],"fragments":[{"kind":"text","text":"- "},{"text":"displayLeftView:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/displayLeftView:","abstract":[{"type":"text","text":"Displays a view on the left side of the text."},{"type":"text","text":" "},{"type":"text","text":"The layout is defined by the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"},{"type":"text","text":"."}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithCustomView:styleName:completion:":{"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithCustomView:styleName:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithcustomview:stylename:completion:","navigatorTitle":[{"text":"presentWithCustomView:styleName:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithCustomView:styleName:completion:","abstract":[{"text":"Present a notification using a custom subview.","type":"text"}],"title":"presentWithCustomView:styleName:completion:","type":"topic","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:completion:":{"title":"presentWithText:completion:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:completion:","type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:completion:","abstract":[{"type":"text","text":"Present a notification using the current default style."}],"navigatorTitle":[{"kind":"identifier","text":"presentWithText:completion:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithText:completion:","kind":"identifier"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"title":"StatusBarNotificationLeftViewStyle","kind":"symbol","navigatorTitle":[{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/updateSubtitle:":{"fragments":[{"kind":"text","text":"- "},{"text":"updateSubtitle:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Updates the subtitle of an existing notification without animation."}],"role":"symbol","type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/updateSubtitle:","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/updatesubtitle:","title":"updateSubtitle:","navigatorTitle":[{"kind":"identifier","text":"updateSubtitle:"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenterPrepareStyleBlock":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterPrepareStyleBlock","title":"JDStatusBarNotificationPresenterPrepareStyleBlock","abstract":[{"text":"Creates a modified copy of an existing ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},{"type":"text","text":" instance."}],"role":"symbol","fragments":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterPrepareStyleBlock"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenterpreparestyleblock"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/setWindowScene:":{"fragments":[{"text":"- ","kind":"text"},{"text":"setWindowScene:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Lets you set an explicit "},{"code":"UIWindowScene","type":"codeVoice"},{"type":"text","text":", in which notifications should be presented in. In most cases you don’t need to set this."}],"role":"symbol","type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/setWindowScene:","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/setwindowscene:","title":"setWindowScene:","navigatorTitle":[{"kind":"identifier","text":"setWindowScene:"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/addStyleNamed:basedOnStyle:prepare:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"addStyleNamed:basedOnStyle:prepare:"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/addStyleNamed:basedOnStyle:prepare:","title":"addStyleNamed:basedOnStyle:prepare:","abstract":[{"type":"text","text":"Adds a new named style based on an included style."},{"text":" ","type":"text"},{"text":"This can later be used by referencing it using the ","type":"text"},{"code":"styleName","type":"codeVoice"},{"type":"text","text":" - or by using the return value directly."}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"addStyleNamed:basedOnStyle:prepare:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/addstylenamed:basedonstyle:prepare:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithCustomView:sizingController:styleName:completion:":{"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithCustomView:sizingController:styleName:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithcustomview:sizingcontroller:stylename:completion:","navigatorTitle":[{"text":"presentWithCustomView:sizingController:styleName:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithCustomView:sizingController:styleName:completion:","abstract":[{"text":"Present a notification using a custom subview.","type":"text"}],"title":"presentWithCustomView:sizingController:styleName:completion:","type":"topic","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenterCompletionBlock":{"kind":"symbol","role":"symbol","title":"JDStatusBarNotificationPresenterCompletionBlock","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenterCompletionBlock","fragments":[{"text":"JDStatusBarNotificationPresenterCompletionBlock","kind":"identifier"}],"abstract":[{"type":"text","text":"Called upon animation completion."}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresentercompletionblock"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:dismissAfterDelay:includedStyle:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentWithText:dismissAfterDelay:includedStyle:"}],"kind":"symbol","abstract":[{"text":"Present a notification using an existing ","type":"text"},{"type":"codeVoice","code":"includedStyle"},{"text":".","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:dismissafterdelay:includedstyle:","navigatorTitle":[{"text":"presentWithText:dismissAfterDelay:includedStyle:","kind":"identifier"}],"title":"presentWithText:dismissAfterDelay:includedStyle:","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:includedStyle:","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/animateProgressBarToPercentage:animationDuration:completion:":{"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/animateprogressbartopercentage:animationduration:completion:","kind":"symbol","role":"symbol","title":"animateProgressBarToPercentage:animationDuration:completion:","navigatorTitle":[{"kind":"identifier","text":"animateProgressBarToPercentage:animationDuration:completion:"}],"fragments":[{"text":"- ","kind":"text"},{"text":"animateProgressBarToPercentage:animationDuration:completion:","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/animateProgressBarToPercentage:animationDuration:completion:","abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/sharedPresenter":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/sharedPresenter","kind":"symbol","abstract":[{"text":"Provides access to the presenter singleton. This is the entry point to present, style and dismiss notifications.","type":"text"}],"type":"topic","fragments":[{"text":"+ ","kind":"text"},{"text":"sharedPresenter","kind":"identifier"}],"navigatorTitle":[{"text":"sharedPresenter","kind":"identifier"}],"title":"sharedPresenter","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/sharedpresenter","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/presentWithText:dismissAfterDelay:customStyle:":{"fragments":[{"text":"- ","kind":"text"},{"text":"presentWithText:dismissAfterDelay:customStyle:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"presentWithText:dismissAfterDelay:customStyle:"}],"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/presentWithText:dismissAfterDelay:customStyle:","kind":"symbol","title":"presentWithText:dismissAfterDelay:customStyle:","role":"symbol","abstract":[{"type":"text","text":"Present a notification using a specified "},{"code":"customStyle","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/presentwithtext:dismissafterdelay:customstyle:"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/JDStatusBarNotificationPresenter/dismissWithCompletion:":{"navigatorTitle":[{"kind":"identifier","text":"dismissWithCompletion:"}],"abstract":[{"text":"Dismisses any currently displayed notification immediately using an animation.","type":"text"}],"fragments":[{"text":"- ","kind":"text"},{"text":"dismissWithCompletion:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"dismissWithCompletion:","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/JDStatusBarNotificationPresenter\/dismissWithCompletion:","role":"symbol","url":"\/documentation\/jdstatusbarnotification\/jdstatusbarnotificationpresenter\/dismisswithcompletion:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JDStatusBarNotificationStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace"},{"value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"op":"replace","value":"JDStatusBarNotificationIncludedStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationIncludedStyle"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/title","value":"JDStatusBarNotificationPresenterCustomViewSizingController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCustomViewSizingController"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","value":"JDStatusBarNotificationLeftViewStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationLeftViewStyle","kind":"identifier"}]}]}]}