{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"NotificationPresenter","kind":"identifier"}],"roleHeading":"Structure","externalID":"s:23JDStatusBarNotification0C9PresenterV","title":"NotificationPresenter","role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/notificationpresenter"]}],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The NotificationPresenter let’s you present notifications below the statusBar."},{"type":"text","text":" "},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NotificationPresenter"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"To customize the appearance, see the ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"Customize the style","type":"text"}]},{"type":"text","text":" section. To see all customization"},{"type":"text","text":" "},{"text":"options, see the ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},{"text":" documentation.","type":"text"}]},{"inlineContent":[{"type":"text","text":"While a notification is displayed, a separate window is presented on top of your application"},{"type":"text","text":" "},{"type":"text","text":"window. Upon dismissal this window, its view controller and all its views are removed from"},{"text":" ","type":"text"},{"type":"text","text":"memory. The presenter class itself is a singleton which will stay in memory for the lifetime of"},{"text":" ","type":"text"},{"type":"text","text":"your application once it was created. The default "},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","isActive":true},{"text":" and any styles","type":"text"},{"type":"text","text":" "},{"text":"added by the user also stay in memory permanently.","type":"text"}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification"]]},"topicSections":[{"title":"Retrieve the presenter","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/shared"]},{"title":"Present a notification","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/Completion","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(_:subtitle:styleName:duration:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(_:subtitle:includedStyle:duration:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentCustomView(_:sizingController:styleName:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(styleName:viewBuilder:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController"],"title":"Present a notification (using a custom view)"},{"title":"Dismiss a notification","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:after:completion:)"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/PrepareStyleClosure","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateDefaultStyle(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(named:usingStyle:prepare:)"],"title":"Customize the style (Appearance & Behavior)"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(at:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(to:duration:completion:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)"],"title":"Display supplementary views"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/isVisible","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateTitle(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateSubtitle(_:)","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/setWindowScene(_:)"],"title":"Additional Presenter APIs"}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/Completion":{"title":"NotificationPresenter.Completion","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/Completion","type":"topic","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/completion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Completion"}],"navigatorTitle":[{"kind":"identifier","text":"Completion"}],"kind":"symbol","abstract":[{"type":"text","text":"Called upon animation completion."}],"role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayProgressBar(at:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayProgressBar","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayprogressbar(at:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayProgressBar(at:)","title":"displayProgressBar(at:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Displays a progress bar at the given "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"type":"topic","title":"StatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"text":"A Style defines the appeareance of a notification.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/updateDefaultStyle(_:)":{"kind":"symbol","title":"updateDefaultStyle(_:)","role":"symbol","abstract":[{"type":"text","text":"Defines a new default style."},{"type":"text","text":" "},{"text":"The new style will be used in all future presentations that have no specific style specified.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/updatedefaultstyle(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateDefaultStyle"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV19PrepareStyleClosurea","text":"PrepareStyleClosure"},{"kind":"text","text":")"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateDefaultStyle(_:)","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/updateSubtitle(_:)":{"abstract":[{"type":"text","text":"Updates the subtitle of an existing notification without animation."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/updatesubtitle(_:)","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateSubtitle(_:)","title":"updateSubtitle(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateSubtitle","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/setWindowScene(_:)":{"role":"symbol","title":"setWindowScene(_:)","abstract":[{"text":"Lets you set an explicit ","type":"text"},{"type":"codeVoice","code":"UIWindowScene"},{"type":"text","text":", in which notifications should be presented in. In most cases you don’t need to set this."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/setWindowScene(_:)","type":"topic","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/setwindowscene(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"setWindowScene","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIWindowScene","preciseIdentifier":"c:objc(cs)UIWindowScene"},{"kind":"text","text":")"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"title":"StatusBarNotificationLeftViewStyle","kind":"symbol","navigatorTitle":[{"text":"StatusBarNotificationLeftViewStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator.","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayLeftView(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"displayLeftView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayleftview(_:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayLeftView(_:)","title":"displayLeftView(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Displays a view on the left side of the text."},{"type":"text","text":" "},{"type":"text","text":"The layout is defined by the "},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","isActive":true},{"type":"text","text":"."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/PrepareStyleClosure":{"title":"NotificationPresenter.PrepareStyleClosure","kind":"symbol","role":"symbol","abstract":[{"text":"Creates a modified copy of an existing ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","type":"reference","isActive":true},{"text":" instance.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/preparestyleclosure","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrepareStyleClosure"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/PrepareStyleClosure","type":"topic","navigatorTitle":[{"text":"PrepareStyleClosure","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/updateTitle(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateTitle"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Updates the title of an existing notification without animation."}],"type":"topic","role":"symbol","title":"updateTitle(_:)","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/updateTitle(_:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/updatetitle(_:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(_:subtitle:includedStyle:duration:completion:)":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(_:subtitle:includedStyle:duration:completion:)","abstract":[{"type":"text","text":"Present a notification using an included style."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(_:subtitle:includedstyle:duration:completion:)","kind":"symbol","title":"present(_:subtitle:includedStyle:duration:completion:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"present"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"subtitle"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"includedStyle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","kind":"typeIdentifier","text":"IncludedStatusBarNotificationStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Completion","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter":{"type":"topic","title":"NotificationPresenter","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NotificationPresenter"}],"abstract":[{"text":"The NotificationPresenter let’s you present notifications below the statusBar.","type":"text"},{"text":" ","type":"text"},{"text":"You can customize the style (colors, fonts, etc.) and animations. It supports notch","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and no-notch devices, landscape & portrait layouts and Drag-to-Dismiss. It can display a"},{"text":" ","type":"text"},{"type":"text","text":"title, a subtitle, an activity indicator, an animated progress bar & custom views out of the box."}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"NotificationPresenter","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/animateProgressBar(to:duration:completion:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animateProgressBar"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","text":"Completion"},{"text":"?)","kind":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/animateprogressbar(to:duration:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/animateProgressBar(to:duration:completion:)","title":"animateProgressBar(to:duration:completion:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Displays a progress bar and animates it to the provided "},{"type":"codeVoice","code":"percentage"},{"type":"text","text":"."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/dismiss(animated:after:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismiss"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"after"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","kind":"typeIdentifier","text":"Completion"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/dismiss(animated:after:completion:)","type":"topic","kind":"symbol","title":"dismiss(animated:after:completion:)","abstract":[{"text":"Dismisses any currently displayed notification animated - after the provided delay, if provided.","type":"text"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/dismiss(animated:after:completion:)"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenterCustomViewSizingController":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresentercustomviewsizingcontroller","navigatorTitle":[{"text":"NotificationPresenterCustomViewSizingController","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenterCustomViewSizingController","abstract":[{"text":"A protocol for a custom controller, which controls the size of a presented custom view.","type":"text"}],"title":"NotificationPresenterCustomViewSizingController","type":"topic","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/IncludedStatusBarNotificationStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IncludedStatusBarNotificationStyle","kind":"identifier"}],"type":"topic","title":"IncludedStatusBarNotificationStyle","abstract":[{"text":"These included styles let you easily change the visual appearance of a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"notification without creating your own custom style."}],"url":"\/documentation\/jdstatusbarnotification\/includedstatusbarnotificationstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/IncludedStatusBarNotificationStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IncludedStatusBarNotificationStyle"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/addStyle(named:usingStyle:prepare:)":{"title":"addStyle(named:usingStyle:prepare:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/addStyle(named:usingStyle:prepare:)","type":"topic","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/addstyle(named:usingstyle:prepare:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addStyle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"named","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"usingStyle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@JDStatusBarNotificationIncludedStyle","text":"IncludedStatusBarNotificationStyle","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"prepare"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV19PrepareStyleClosurea","text":"PrepareStyleClosure"},{"text":") -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Adds a new named style - based on an included style, if given.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This can later be used by referencing it using the "},{"code":"styleName","type":"codeVoice"},{"type":"text","text":" - or by using the return value directly."}],"role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/presentCustomView(_:sizingController:styleName:completion:)":{"title":"presentCustomView(_:sizingController:styleName:completion:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentCustomView(_:sizingController:styleName:completion:)","type":"topic","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentcustomview(_:sizingcontroller:stylename:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentCustomView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sizingController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NotificationPresenterCustomViewSizingController","preciseIdentifier":"c:objc(pl)JDStatusBarNotificationPresenterCustomViewSizingController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"styleName","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona","text":"Completion","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"kind":"symbol","abstract":[{"text":"Present a notification using a custom subview.","type":"text"}],"role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/displayActivityIndicator(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayActivityIndicator","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/displayactivityindicator(_:)","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/displayActivityIndicator(_:)","title":"displayActivityIndicator(_:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Displays an activity indicator as the notifications left view."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/shared":{"title":"shared","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/shared","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NotificationPresenter","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/shared","abstract":[{"text":"Provides access to the shared presenter. This is the entry point to present, style and dismiss notifications.","type":"text"}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/present(_:subtitle:styleName:duration:completion:)":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/present(_:subtitle:styleName:duration:completion:)","abstract":[{"type":"text","text":"Present a notification using the default style or a named style."}],"url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/present(_:subtitle:stylename:duration:completion:)","title":"present(_:subtitle:styleName:duration:completion:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"present","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"subtitle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"styleName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Completion","kind":"typeIdentifier","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/isVisible":{"abstract":[{"type":"text","text":"Let’s you check if a notification is currently displayed."}],"title":"isVisible","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/isvisible","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/isVisible","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isVisible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"type":"topic","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"url":"\/documentation\/jdstatusbarnotification","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","role":"collection","kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/NotificationPresenter/presentSwiftView(styleName:viewBuilder:completion:)":{"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/NotificationPresenter\/presentSwiftView(styleName:viewBuilder:completion:)","type":"topic","role":"symbol","title":"presentSwiftView(styleName:viewBuilder:completion:)","url":"\/documentation\/jdstatusbarnotification\/notificationpresenter\/presentswiftview(stylename:viewbuilder:completion:)","abstract":[{"text":"Present a notification using a custom SwiftUI view.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentSwiftView"},{"kind":"text","text":"("},{"text":"styleName","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"viewBuilder"},{"kind":"text","text":": () -> "},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI4ViewP","text":"View"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Completion","preciseIdentifier":"s:23JDStatusBarNotification0C9PresenterV10Completiona"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}]}},"variantOverrides":[{"patch":[{"value":"JDStatusBarNotificationStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}]},{"value":"JDStatusBarNotificationLeftViewStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationLeftViewStyle","kind":"identifier"}]},{"op":"replace","value":"JDStatusBarNotificationPresenterCustomViewSizingController","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationPresenterCustomViewSizingController"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1NotificationPresenterCustomViewSizingController\/fragments"},{"value":"JDStatusBarNotificationIncludedStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1IncludedStatusBarNotificationStyle\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationIncludedStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}