{"seeAlsoSections":[{"title":"Notification Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"title":"StatusBarNotificationLeftViewStyle","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)JDStatusBarNotificationLeftViewStyle","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}]},"abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"sections":[],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying","doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject","doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP","doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/SQ","doc:\/\/calimarkus.JDStatusBarNotification\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/alignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offset","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offsetX","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/spacing","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/tintColor"]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle/alignment":{"role":"symbol","title":"alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationLeftViewAlignment","preciseIdentifier":"c:@E@JDStatusBarNotificationLeftViewAlignment"}],"abstract":[{"type":"text","text":"The alignment of the left-view. The default is "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment\/centerWithText"},{"type":"text","text":" "},{"type":"text","text":"If no title or subtitle is set, the left-view is always fully centered."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/alignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alignment"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle\/alignment"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle/tintColor":{"role":"symbol","title":"tintColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Sets the tint color of the left-view. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/tintColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"tintColor"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle\/tintcolor"},"doc://calimarkus.JDStatusBarNotification/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SQ"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle":{"role":"symbol","title":"StatusBarNotificationBackgroundStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationBackgroundStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationBackgroundStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationPillStyle":{"role":"symbol","title":"StatusBarNotificationPillStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationPillStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the pill, when using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationPillStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationpillstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"role":"symbol","title":"StatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"role":"symbol","title":"StatusBarNotificationProgressBarStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the progress bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle"},"doc://calimarkus.JDStatusBarNotification/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SH"},"doc://calimarkus.JDStatusBarNotification/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle/offsetX":{"deprecated":true,"role":"symbol","title":"offsetX","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offsetX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"An optional offset to adjust the left-views x position. Default 0.0."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offsetX","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"offsetX"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle\/offsetx"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","title":"StatusBarNotificationLeftViewStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle/spacing":{"role":"symbol","title":"spacing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"spacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The minimum distance between the left-view and the text. Defaults to 5.0."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/spacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"spacing"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle\/spacing"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle/offset":{"role":"symbol","title":"offset","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"offset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"type":"text","text":"An optional offset to adjust the left-views position. Default is "},{"type":"codeVoice","code":"CGPointZero"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"offset"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle\/offset"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"role":"symbol","title":"StatusBarNotificationBackgroundType.pill","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pill"}],"abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill"},"doc://calimarkus.JDStatusBarNotification/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP"},"doc://calimarkus.JDStatusBarNotification/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment/centerWithText":{"role":"symbol","title":"StatusBarNotificationLeftViewAlignment.centerWithText","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"centerWithText"}],"abstract":[{"type":"text","text":"Centers the left-view together with the text. The left-view will be positioned at the leading edge of the text. The text is left-aligned. This is the default."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment\/centerWithText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentCenterWithText"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment\/centerwithtext"},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject"},"doc://calimarkus.JDStatusBarNotification/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP"},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationTextStyle":{"role":"symbol","title":"StatusBarNotificationTextStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of a text label."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationtextstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationLeftViewStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/alignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offset","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/offsetX","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/spacing","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle\/tintColor"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Notification Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1alignment\/title","value":"alignment"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1alignment\/fragments","value":[{"kind":"identifier","text":"alignment"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1tintColor\/title","value":"tintColor"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1tintColor\/fragments","value":[{"kind":"identifier","text":"tintColor"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/title","value":"JDStatusBarNotificationBackgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/title","value":"JDStatusBarNotificationPillStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPillStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","value":"JDStatusBarNotificationProgressBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1offsetX\/title","value":"offsetX"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1offsetX\/fragments","value":[{"kind":"identifier","text":"offsetX"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","value":"JDStatusBarNotificationLeftViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1spacing\/title","value":"spacing"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1spacing\/fragments","value":[{"kind":"identifier","text":"spacing"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1offset\/title","value":"offset"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle~1offset\/fragments","value":[{"kind":"identifier","text":"offset"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title","value":"JDStatusBarNotificationBackgroundTypePill"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment~1centerWithText\/title","value":"JDStatusBarNotificationLeftViewAlignmentCenterWithText"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment~1centerWithText\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignmentCenterWithText"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/title","value":"JDStatusBarNotificationTextStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationTextStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}