{"relationshipsSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/SQ","doc:\/\/calimarkus.JDStatusBarNotification\/SH","doc:\/\/calimarkus.JDStatusBarNotification\/SY","doc:\/\/calimarkus.JDStatusBarNotification\/s8SendableP"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle"]}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle"},"metadata":{"modules":[{"name":"JDStatusBarNotification"}],"role":"symbol","symbolKind":"enum","externalID":"c:@E@JDStatusBarNotificationSystemBarStyle","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationSystemBarStyle"}],"title":"StatusBarNotificationSystemBarStyle","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Note that if you use ","type":"text"},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","type":"reference","isActive":true},{"type":"text","text":", this is ignored."},{"text":" ","type":"text"},{"type":"text","text":"The default is "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/defaultStyle","type":"reference","isActive":true},{"text":".","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/darkContent","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/defaultStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/lightContent"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/init(rawValue:)"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/Equatable-Implementations","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/RawRepresentable-Implementations"]}],"seeAlsoSections":[{"title":"Style Enumerations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"],"generated":true}],"abstract":[{"type":"text","text":"Defines which "},{"type":"codeVoice","code":"UIStatusBarStyle"},{"type":"text","text":" should be used during presentation."}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://calimarkus.JDStatusBarNotification/SY":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SY","title":"Swift.RawRepresentable"},"doc://calimarkus.JDStatusBarNotification/SH":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SH","title":"Swift.Hashable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/lightContent":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/lightContent","title":"StatusBarNotificationSystemBarStyle.lightContent","kind":"symbol","abstract":[{"type":"text","text":"Forces light status bar contents ("},{"type":"codeVoice","code":"UIStatusBarStyleLightContent"},{"type":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleLightContent"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/lightcontent","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lightContent","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"title":"StatusBarNotificationAnimationType","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationAnimationType","kind":"identifier"}],"abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"kind":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","type":"topic","url":"\/documentation\/jdstatusbarnotification","title":"JDStatusBarNotification","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s8SendableP","title":"Swift.Sendable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/equatable-implementations"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"abstract":[{"text":"Defines the position of the progress bar, when used.","type":"text"}],"role":"symbol","title":"StatusBarNotificationProgressBarPosition","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}]},"doc://calimarkus.JDStatusBarNotification/SQ":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SQ","title":"Swift.Equatable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","type":"topic","abstract":[{"text":"Defines which ","type":"text"},{"code":"UIStatusBarStyle","type":"codeVoice"},{"type":"text","text":" should be used during presentation."}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"title":"StatusBarNotificationSystemBarStyle","role":"symbol"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType":{"role":"symbol","abstract":[{"type":"text","text":"Defines the appearance of the notification background."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"type":"topic","title":"StatusBarNotificationBackgroundType","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"type":"topic","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","title":"StatusBarNotificationBackgroundType.pill","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"pill","kind":"identifier"}],"navigatorTitle":[{"text":"JDStatusBarNotificationBackgroundTypePill","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/darkContent":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/darkcontent","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"darkContent","kind":"identifier"}],"title":"StatusBarNotificationSystemBarStyle.darkContent","abstract":[{"type":"text","text":"Forces dark status bar contents ("},{"type":"codeVoice","code":"UIStatusBarStyleDarkContent"},{"text":")","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleDarkContent"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/darkContent"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/rawrepresentable-implementations"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle/defaultStyle":{"type":"topic","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/defaultStyle","title":"StatusBarNotificationSystemBarStyle.defaultStyle","kind":"symbol","abstract":[{"type":"text","text":"Matches the current viewController \/ window."}],"navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleDefaultStyle"}],"role":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle\/defaultstyle","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultStyle"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment":{"abstract":[{"type":"text","text":"Defines the appearance of a left-view, if set. This includes the activity indicator."}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment","title":"StatusBarNotificationLeftViewAlignment","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","navigatorTitle":[{"text":"StatusBarNotificationLeftViewAlignment","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationStyle","kind":"identifier"}],"title":"StatusBarNotificationStyle","navigatorTitle":[{"text":"StatusBarNotificationStyle","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationSystemBarStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/darkContent","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/defaultStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle\/lightContent"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Style Enumerations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1lightContent\/title","value":"JDStatusBarNotificationSystemBarStyleLightContent"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleLightContent"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1lightContent\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title","op":"replace","value":"JDStatusBarNotificationAnimationType"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationAnimationType"}]},{"value":"JDStatusBarNotificationProgressBarPosition","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationProgressBarPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title","op":"replace","value":"JDStatusBarNotificationSystemBarStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments","value":[{"text":"JDStatusBarNotificationSystemBarStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/title","value":"JDStatusBarNotificationBackgroundType","op":"replace"},{"value":[{"text":"JDStatusBarNotificationBackgroundType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/fragments"},{"op":"replace","value":"JDStatusBarNotificationBackgroundTypePill","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments","op":"replace"},{"value":"JDStatusBarNotificationSystemBarStyleDarkContent","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1darkContent\/title","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1darkContent\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationSystemBarStyleDarkContent","kind":"identifier"}]},{"op":"replace","value":"JDStatusBarNotificationSystemBarStyleDefaultStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1defaultStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle~1defaultStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyleDefaultStyle"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/title","value":"JDStatusBarNotificationLeftViewAlignment","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/fragments","value":[{"text":"JDStatusBarNotificationLeftViewAlignment","kind":"identifier"}]},{"value":"JDStatusBarNotificationStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]}]}]}