{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/fullWidth","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill"]},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/Equatable-Implementations","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"metadata":{"symbolKind":"enum","title":"StatusBarNotificationBackgroundType","navigatorTitle":[{"text":"StatusBarNotificationBackgroundType","kind":"identifier"}],"role":"symbol","modules":[{"name":"JDStatusBarNotification"}],"roleHeading":"Enumeration","externalID":"c:@E@JDStatusBarNotificationBackgroundType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StatusBarNotificationBackgroundType","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Defines the appearance of the notification background."}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"]]},"relationshipsSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/SQ","doc:\/\/calimarkus.JDStatusBarNotification\/SH","doc:\/\/calimarkus.JDStatusBarNotification\/SY","doc:\/\/calimarkus.JDStatusBarNotification\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"seeAlsoSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"],"title":"Style Enumerations","generated":true}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"StatusBarNotificationAnimationType","kind":"identifier"}],"abstract":[{"text":"Defines the animation used during presentation and dismissal of the notification.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"type":"topic","title":"StatusBarNotificationAnimationType","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType"},"doc://calimarkus.JDStatusBarNotification/SH":{"type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SH","title":"Swift.Hashable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"title":"StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/fullWidth":{"type":"topic","title":"StatusBarNotificationBackgroundType.fullWidth","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypeFullWidth"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/fullWidth","kind":"symbol","role":"symbol","abstract":[{"text":"The background covers the full display width and the full status bar + navbar height.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/fullwidth","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fullWidth","kind":"identifier"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/Equatable-Implementations","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/equatable-implementations"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"title":"StatusBarNotificationSystemBarStyle","abstract":[{"text":"Defines which ","type":"text"},{"type":"codeVoice","code":"UIStatusBarStyle"},{"type":"text","text":" should be used during presentation."}],"kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","role":"symbol","navigatorTitle":[{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationSystemBarStyle","kind":"identifier"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle","type":"topic"},"doc://calimarkus.JDStatusBarNotification/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s8SendableP","type":"unresolvable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType":{"kind":"symbol","role":"symbol","title":"StatusBarNotificationBackgroundType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"abstract":[{"type":"text","text":"Defines the appearance of the notification background."}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"title":"StatusBarNotificationBackgroundType.pill","role":"symbol","navigatorTitle":[{"text":"JDStatusBarNotificationBackgroundTypePill","kind":"identifier"}],"abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pill","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill"},"doc://calimarkus.JDStatusBarNotification/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SY","type":"unresolvable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment":{"kind":"symbol","type":"topic","title":"StatusBarNotificationLeftViewAlignment","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"abstract":[{"text":"Defines the appearance of a left-view, if set. This includes the activity indicator.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"title":"StatusBarNotificationProgressBarPosition","kind":"symbol","abstract":[{"text":"Defines the position of the progress bar, when used.","type":"text"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition","type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/init(rawValue:)","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/RawRepresentable-Implementations":{"type":"topic","kind":"article","abstract":[],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/rawrepresentable-implementations","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations"},"doc://calimarkus.JDStatusBarNotification/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"JDStatusBarNotificationBackgroundType","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JDStatusBarNotificationBackgroundType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/fullWidth","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Style Enumerations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"],"generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JDStatusBarNotificationBackgroundType"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"JDStatusBarNotificationAnimationType","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments","value":[{"text":"JDStatusBarNotificationAnimationType","kind":"identifier"}]},{"value":"JDStatusBarNotificationStyle","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace"},{"op":"replace","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1fullWidth\/title","value":"JDStatusBarNotificationBackgroundTypeFullWidth","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1fullWidth\/fragments","op":"replace","value":[{"text":"JDStatusBarNotificationBackgroundTypeFullWidth","kind":"identifier"}]},{"value":"JDStatusBarNotificationSystemBarStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"}]},{"op":"replace","value":"JDStatusBarNotificationBackgroundType","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/title"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/fragments","value":[{"text":"JDStatusBarNotificationBackgroundType","kind":"identifier"}]},{"value":"JDStatusBarNotificationBackgroundTypePill","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/title","value":"JDStatusBarNotificationLeftViewAlignment","op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/fragments","op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignment"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/title","value":"JDStatusBarNotificationProgressBarPosition","op":"replace"},{"value":[{"text":"JDStatusBarNotificationProgressBarPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/fragments"}]}]}