{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying","doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject","doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP","doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/SQ","doc:\/\/calimarkus.JDStatusBarNotification\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundColor","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/pillStyle"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification"]]},"metadata":{"navigatorTitle":[{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}],"externalID":"c:objc(cs)JDStatusBarNotificationBackgroundStyle","title":"StatusBarNotificationBackgroundStyle","symbolKind":"class","role":"symbol","roleHeading":"Class","modules":[{"name":"JDStatusBarNotification"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}]},"seeAlsoSections":[{"title":"Notification Style","generated":true,"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","role":"symbol","navigatorTitle":[{"text":"StatusBarNotificationProgressBarStyle","kind":"identifier"}],"title":"StatusBarNotificationProgressBarStyle","abstract":[{"text":"Defines the appeareance of the progress bar.","type":"text"}],"kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle","type":"topic"},"doc://calimarkus.JDStatusBarNotification/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SH"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","title":"JDStatusBarNotification","url":"\/documentation\/jdstatusbarnotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}]},"doc://calimarkus.JDStatusBarNotification/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP"},"doc://calimarkus.JDStatusBarNotification/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP"},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSCopying":{"title":"NSCopying","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying"},"doc://calimarkus.JDStatusBarNotification/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SQ"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationPillStyle":{"abstract":[{"type":"text","text":"Defines the appeareance of the pill, when using "},{"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","isActive":true}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationpillstyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","navigatorTitle":[{"text":"StatusBarNotificationPillStyle","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"StatusBarNotificationPillStyle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationPillStyle"}]},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject"},"doc://calimarkus.JDStatusBarNotification/s23CustomStringConvertibleP":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle":{"title":"StatusBarNotificationBackgroundStyle","role":"symbol","navigatorTitle":[{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"StatusBarNotificationBackgroundStyle","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"title":"StatusBarNotificationBackgroundType.pill","role":"symbol","navigatorTitle":[{"text":"JDStatusBarNotificationBackgroundTypePill","kind":"identifier"}],"abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pill","kind":"identifier"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill"},"doc://calimarkus.JDStatusBarNotification/objc(cs)NSObject":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/backgroundType":{"title":"backgroundType","role":"symbol","navigatorTitle":[{"text":"backgroundType","kind":"identifier"}],"abstract":[{"type":"text","text":"The background type. Default is "},{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","isActive":true,"type":"reference"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@JDStatusBarNotificationBackgroundType","text":"StatusBarNotificationBackgroundType"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundType","kind":"symbol","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/backgroundtype"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationTextStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"type":"topic","abstract":[{"type":"text","text":"Defines the appeareance of a text label."}],"title":"StatusBarNotificationTextStyle","kind":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationtextstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationTextStyle"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/backgroundColor":{"role":"symbol","type":"topic","title":"backgroundColor","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundColor","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/backgroundcolor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"backgroundColor","kind":"identifier"}],"abstract":[{"text":"The background color of the notification bar","type":"text"}]},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle","kind":"symbol","type":"topic","title":"StatusBarNotificationLeftViewStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle","type":"topic","abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"title":"StatusBarNotificationStyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"role":"symbol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle/pillStyle":{"role":"symbol","type":"topic","title":"pillStyle","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/pillStyle","url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle\/pillstyle","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"pillStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"StatusBarNotificationPillStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationPillStyle"}],"navigatorTitle":[{"text":"pillStyle","kind":"identifier"}],"abstract":[{"text":"Defines the appeareance of the pill, when using ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"JDStatusBarNotificationBackgroundStyle","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"JDStatusBarNotificationBackgroundStyle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundStyle"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundColor","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/backgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle\/pillStyle"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Notification Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"],"generated":true}]},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JDStatusBarNotificationBackgroundStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","op":"replace","value":"JDStatusBarNotificationProgressBarStyle"},{"op":"replace","value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments"},{"value":"JDStatusBarNotificationPillStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/title"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPillStyle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/title","value":"JDStatusBarNotificationBackgroundStyle"},{"op":"replace","value":[{"text":"JDStatusBarNotificationBackgroundStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title","op":"replace","value":"JDStatusBarNotificationBackgroundTypePill"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}]},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundType\/title","value":"backgroundType","op":"replace"},{"value":[{"kind":"identifier","text":"backgroundType"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundType\/fragments"},{"value":"JDStatusBarNotificationTextStyle","op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/title"},{"value":[{"text":"JDStatusBarNotificationTextStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1backgroundColor\/fragments","value":[{"text":"backgroundColor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","value":"JDStatusBarNotificationLeftViewStyle"},{"op":"replace","value":[{"text":"JDStatusBarNotificationLeftViewStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","op":"replace","value":"JDStatusBarNotificationStyle"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"text":"JDStatusBarNotificationStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1pillStyle\/title","op":"replace","value":"pillStyle"},{"op":"replace","value":[{"kind":"identifier","text":"pillStyle"}],"path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle~1pillStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}