{"seeAlsoSections":[{"title":"Notification Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"title":"StatusBarNotificationStyle","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)JDStatusBarNotificationStyle","modules":[{"name":"JDStatusBarNotification"}],"navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}]},"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"sections":[],"identifier":{"url":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying","doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject","doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP","doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP","doc:\/\/calimarkus.JDStatusBarNotification\/SQ","doc:\/\/calimarkus.JDStatusBarNotification\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification"]]},"topicSections":[{"title":"Notification Bar Behavior","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold"]},{"title":"Styling the text","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/textStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle"]},{"title":"Styling the background","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/backgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle"]},{"title":"Styling supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle"]},{"title":"Style Enumerations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"]}],"variants":[{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/subtitleStyle":{"role":"symbol","title":"subtitleStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitleStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationTextStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the subtitle label."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"subtitleStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/subtitlestyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationTextStyle":{"role":"symbol","title":"StatusBarNotificationTextStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of a text label."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationTextStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationtextstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canSwipeToDismiss":{"role":"symbol","title":"canSwipeToDismiss","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canSwipeToDismiss"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Defines if the bar can be dismissed by the user swiping up. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canSwipeToDismiss"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/canswipetodismiss"},"doc://calimarkus.JDStatusBarNotification/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s23CustomStringConvertibleP"},"doc://calimarkus.JDStatusBarNotification/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SQ"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/leftViewStyle":{"role":"symbol","title":"leftViewStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftViewStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationLeftViewStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationLeftViewStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftViewStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/leftviewstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/progressBarStyle":{"role":"symbol","title":"progressBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationProgressBarStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationProgressBarStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the progress bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"progressBarStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/progressbarstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType/pill":{"role":"symbol","title":"StatusBarNotificationBackgroundType.pill","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pill"}],"abstract":[{"type":"text","text":"The background is a floating pill around the text. The pill size and appearance can be customized. This is the default."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype\/pill"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationSystemBarStyle":{"role":"symbol","title":"StatusBarNotificationSystemBarStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationSystemBarStyle"}],"abstract":[{"type":"text","text":"Defines which "},{"type":"codeVoice","code":"UIStatusBarStyle"},{"type":"text","text":" should be used during presentation."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationSystemBarStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationsystembarstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationPillStyle":{"role":"symbol","title":"StatusBarNotificationPillStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationPillStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the pill, when using "},{"type":"reference","isActive":true,"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType\/pill"}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationPillStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationpillstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/textStyle":{"role":"symbol","title":"textStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationTextStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationTextStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the title label."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/textStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/textstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/backgroundStyle":{"role":"symbol","title":"backgroundStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationBackgroundStyle","preciseIdentifier":"c:objc(cs)JDStatusBarNotificationBackgroundStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/backgroundStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/backgroundstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarStyle":{"role":"symbol","title":"StatusBarNotificationProgressBarStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the progress bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewAlignment":{"role":"symbol","title":"StatusBarNotificationLeftViewAlignment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"abstract":[{"type":"text","text":"Defines the appearance of a left-view, if set. This includes the activity indicator."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewAlignment"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewalignment"},"doc://calimarkus.JDStatusBarNotification/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s7CVarArgP"},"doc://calimarkus.JDStatusBarNotification/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(cs)NSObject"},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSObject"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationAnimationType":{"role":"symbol","title":"StatusBarNotificationAnimationType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"abstract":[{"type":"text","text":"Defines the animation used during presentation and dismissal of the notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationAnimationType"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationanimationtype"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification":{"role":"collection","title":"JDStatusBarNotification","abstract":[{"type":"text","text":"Highly customizable & feature rich notifications displayed below the status bar."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification","kind":"symbol","type":"topic","url":"\/documentation\/jdstatusbarnotification"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundType":{"role":"symbol","title":"StatusBarNotificationBackgroundType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"abstract":[{"type":"text","text":"Defines the appearance of the notification background."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationBackgroundType"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundtype"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/systemStatusBarStyle":{"role":"symbol","title":"systemStatusBarStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"systemStatusBarStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationSystemBarStyle","preciseIdentifier":"c:@E@JDStatusBarNotificationSystemBarStyle"}],"abstract":[{"type":"text","text":"Defines which "},{"type":"codeVoice","code":"UIStatusBarStyle"},{"type":"text","text":" should be used during presentation."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"systemStatusBarStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/systemstatusbarstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canTapToHold":{"role":"symbol","title":"canTapToHold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canTapToHold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Defines if the bar can be touched to prevent a dismissal until the tap is released. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canTapToHold"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/cantaptohold"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/animationType":{"role":"symbol","title":"animationType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"StatusBarNotificationAnimationType","preciseIdentifier":"c:@E@JDStatusBarNotificationAnimationType"}],"abstract":[{"type":"text","text":"Defines the animation used during presentation and dismissal of the notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationType"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/animationtype"},"doc://calimarkus.JDStatusBarNotification/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/s28CustomDebugStringConvertibleP"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle/canDismissDuringUserInteraction":{"role":"symbol","title":"canDismissDuringUserInteraction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDismissDuringUserInteraction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Defines if the bar is allowed to be dismissed while the user touches or pans the view."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canDismissDuringUserInteraction"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle\/candismissduringuserinteraction"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationLeftViewStyle":{"role":"symbol","title":"StatusBarNotificationLeftViewStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of a left-view, if set. It also applies to the activity indicator."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationLeftViewStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationleftviewstyle"},"doc://calimarkus.JDStatusBarNotification/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/objc(pl)NSCopying"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationProgressBarPosition":{"role":"symbol","title":"StatusBarNotificationProgressBarPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"abstract":[{"type":"text","text":"Defines the position of the progress bar, when used."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationProgressBarPosition"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationprogressbarposition"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationBackgroundStyle":{"role":"symbol","title":"StatusBarNotificationBackgroundStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationBackgroundStyle"}],"abstract":[{"type":"text","text":"Defines the appeareance of the notification background."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationBackgroundStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationbackgroundstyle"},"doc://calimarkus.JDStatusBarNotification/documentation/JDStatusBarNotification/StatusBarNotificationStyle":{"role":"symbol","title":"StatusBarNotificationStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"StatusBarNotificationStyle"}],"abstract":[{"type":"text","text":"A Style defines the appeareance of a notification."}],"identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StatusBarNotificationStyle"}],"url":"\/documentation\/jdstatusbarnotification\/statusbarnotificationstyle"},"doc://calimarkus.JDStatusBarNotification/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/calimarkus.JDStatusBarNotification\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Notification Bar Behavior","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/animationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canDismissDuringUserInteraction","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canSwipeToDismiss","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/canTapToHold"]},{"title":"Styling the text","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/textStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/subtitleStyle"]},{"title":"Styling the background","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/backgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/systemStatusBarStyle"]},{"title":"Styling supplementary views","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/progressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationStyle\/leftViewStyle"]},{"title":"Style Enumerations","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationAnimationType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundType","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationSystemBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewAlignment","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarPosition"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Notification Style","identifiers":["doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationTextStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationBackgroundStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationPillStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationProgressBarStyle","doc:\/\/calimarkus.JDStatusBarNotification\/documentation\/JDStatusBarNotification\/StatusBarNotificationLeftViewStyle"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JDStatusBarNotificationStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1subtitleStyle\/title","value":"subtitleStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1subtitleStyle\/fragments","value":[{"kind":"identifier","text":"subtitleStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/title","value":"JDStatusBarNotificationTextStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationTextStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationTextStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/title","value":"canSwipeToDismiss"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canSwipeToDismiss\/fragments","value":[{"kind":"identifier","text":"canSwipeToDismiss"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/title","value":"leftViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1leftViewStyle\/fragments","value":[{"kind":"identifier","text":"leftViewStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/title","value":"progressBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1progressBarStyle\/fragments","value":[{"kind":"identifier","text":"progressBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/title","value":"JDStatusBarNotificationBackgroundTypePill"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType~1pill\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundTypePill"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/title","value":"JDStatusBarNotificationSystemBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationSystemBarStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationSystemBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/title","value":"JDStatusBarNotificationPillStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationPillStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationPillStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1textStyle\/title","value":"textStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1textStyle\/fragments","value":[{"kind":"identifier","text":"textStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1backgroundStyle\/title","value":"backgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1backgroundStyle\/fragments","value":[{"kind":"identifier","text":"backgroundStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/title","value":"JDStatusBarNotificationProgressBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/title","value":"JDStatusBarNotificationLeftViewAlignment"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewAlignment\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewAlignment"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/title","value":"JDStatusBarNotificationAnimationType"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationAnimationType\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationAnimationType"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/title","value":"JDStatusBarNotificationBackgroundType"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundType\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundType"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1systemStatusBarStyle\/title","value":"systemStatusBarStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1systemStatusBarStyle\/fragments","value":[{"kind":"identifier","text":"systemStatusBarStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/title","value":"canTapToHold"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canTapToHold\/fragments","value":[{"kind":"identifier","text":"canTapToHold"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/title","value":"animationType"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1animationType\/fragments","value":[{"kind":"identifier","text":"animationType"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/title","value":"canDismissDuringUserInteraction"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle~1canDismissDuringUserInteraction\/fragments","value":[{"kind":"identifier","text":"canDismissDuringUserInteraction"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/title","value":"JDStatusBarNotificationLeftViewStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationLeftViewStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationLeftViewStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/title","value":"JDStatusBarNotificationProgressBarPosition"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationProgressBarPosition\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationProgressBarPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/title","value":"JDStatusBarNotificationBackgroundStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationBackgroundStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationBackgroundStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/title","value":"JDStatusBarNotificationStyle"},{"op":"replace","path":"\/references\/doc:~1~1calimarkus.JDStatusBarNotification~1documentation~1JDStatusBarNotification~1StatusBarNotificationStyle\/fragments","value":[{"kind":"identifier","text":"JDStatusBarNotificationStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}